In [399]:
import pandas as pd
import numpy as np

In [400]:
tr_df = pd.read_csv("./home-data-for-ml-course/train.csv", index_col="Id")
tr_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [401]:
tr_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   str
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   str
 5   Alley          91 non-null     str
 6   LotShape       1460 non-null   str
 7   LandContour    1460 non-null   str
 8   Utilities      1460 non-null   str
 9   LotConfig      1460 non-null   str
 10  LandSlope      1460 non-null   str
 11  Neighborhood   1460 non-null   str
 12  Condition1     1460 non-null   str
 13  Condition2     1460 non-null   str
 14  BldgType       1460 non-null   str
 15  HouseStyle     1460 non-null   str
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   str
 21  RoofMatl       1460 non-null   str
 22  Exterior1st    1460 non-null   str
 23  Exterior2nd    1460 non-null   str
 24  MasVnrType     588 non-null    str
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   str
 27  ExterCond      1460 non-null   str
 28  Foundation     1460 non-null   str
 29  BsmtQual       1423 non-null   str
 30  BsmtCond       1423 non-null   str
 31  BsmtExposure   1422 non-null   str
 32  BsmtFinType1   1423 non-null   str
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   str
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   str
 39  HeatingQC      1460 non-null   str
 40  CentralAir     1460 non-null   str
 41  Electrical     1459 non-null   str
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   str
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   str
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    str
 57  GarageType     1379 non-null   str
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   str
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   str
 63  GarageCond     1379 non-null   str
 64  PavedDrive     1460 non-null   str
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      str
 72  Fence          281 non-null    str
 73  MiscFeature    54 non-null     str
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   str
 78  SaleCondition  1460 non-null   str
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), str(43)
memory usage: 912.6 KB

In [402]:
def trans_features(df):
    new_df = df.copy()
    new_df["Street"] = df["Street"].map({"Grvl": 0, "Pave": 1}).astype("int64")
    new_df["Alley"] = df["Alley"].map({"Grvl": 1, "Pave": 2}).fillna(0).astype("int64")
    new_df["LotShape"] = df["LotShape"].map({"Reg": 3, "IR1": 2, "IR2": 1, "IR3": 0}).astype("int64")
    new_df["LandContour"] = df["LandContour"].map({"Lvl": 3, "Bnk": 2, "HLS": 1, "Low": 0}).astype("int64")
    new_df["Utilities"] = df["Utilities"].map({"AllPub": 3, "NoSewr": 2, "NoSeWa": 1, "ELO": 0}).astype("int64")
    new_df["LandSlope"] = df["LandSlope"].map({"Gtl": 2, "Mod": 1, "Sev": 0}).astype("int64")
    new_df["ExterQual"] = df["ExterQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
    new_df["ExterCond"] = df["ExterCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
    new_df["BsmtQual"] = df["BsmtQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
    new_df["BsmtCond"] = df["BsmtCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
    new_df["BsmtExposure"] = df["BsmtExposure"].map({"Gd": 4, "Av": 3, "Mn": 2, "No": 1}).fillna(0).astype("int64")
    new_df["BsmtFinType1"] = df["BsmtFinType1"].map({"GLQ": 6, "ALQ": 5, "BLQ": 4, "Rec": 3, "LwQ": 2, "Unf": 1}).fillna(0).astype("int64")
    new_df["BsmtFinType2"] = df["BsmtFinType2"].map({"GLQ": 6, "ALQ": 5, "BLQ": 4, "Rec": 3, "LwQ": 2, "Unf": 1}).fillna(0).astype("int64")
    new_df["HeatingQC"] = df["HeatingQC"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
    new_df["CentralAir"] = df["CentralAir"].map({"N": 0, "Y": 1}).astype("int64")
    new_df["KitchenQual"] = df["KitchenQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
    new_df["Functional"] = df["Functional"].map({"Typ": 8, "Min1": 7, "Min2": 6, "Mod": 5, "Maj1": 4, "Maj2": 3, "Sev": 2, "Sal": 1}).astype("int64")
    new_df["FireplaceQu"] = df["FireplaceQu"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
    new_df["GarageQual"] = df["GarageQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
    new_df["GarageCond"] = df["GarageCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
    new_df["PavedDrive"] = df["PavedDrive"].map({"Y": 2, "P": 1, "N": 0}).astype("int64")
    new_df["PoolQC"] = df["PoolQC"].map({"Ex": 4, "Gd": 3, "TA": 2, "Fa": 1,}).fillna(0).astype("int64")

    new_df["LotFrontage"] = df["LotFrontage"].fillna(0)
    new_df["MasVnrArea"] = df["MasVnrArea"].fillna(0)
    new_df["GarageYrBlt"] = df["GarageYrBlt"].fillna(0)

    return new_df

In [ ]:
def normalize_features(train_df, curr_df):
    curr_df["LotFrontage"] = (curr_df["LotFrontage"] - train_df["LotFrontage"].mean()) / train_df["LotFrontage"].std()
    curr_df["LotArea"] = (curr_df["LotArea"] - train_df["LotArea"].mean()) / train_df["LotArea"].std()
    curr_df["YearBuilt"] = (curr_df["YearBuilt"] - train_df["YearBuilt"].mean()) / train_df["YearBuilt"].std()
    curr_df["YearRemodAdd"] = (curr_df["YearRemodAdd"] - train_df["YearRemodAdd"].mean()) / train_df["YearRemodAdd"].std()
    curr_df["MasVnrArea"] = (curr_df["MasVnrArea"] - train_df["MasVnrArea"].mean()) / train_df["MasVnrArea"].std()
    curr_df["BsmtFinSF1"] = (curr_df["BsmtFinSF1"] - train_df["BsmtFinSF1"].mean()) / train_df["BsmtFinSF1"].std()
    curr_df["BsmtFinSF2"] = (curr_df["BsmtFinSF2"] - train_df["BsmtFinSF2"].mean()) / train_df["BsmtFinSF2"].std()
    curr_df["BsmtUnfSF"] = (curr_df["BsmtUnfSF"] - train_df["BsmtUnfSF"].mean()) / train_df["BsmtUnfSF"].std()
    curr_df["TotalBsmtSF"] = (curr_df["TotalBsmtSF"] - train_df["TotalBsmtSF"].mean()) / train_df["TotalBsmtSF"].std()
    curr_df["1stFlrSF"] = (curr_df["1stFlrSF"] - train_df["1stFlrSF"].mean()) / train_df["1stFlrSF"].std()
    curr_df["2ndFlrSF"] = (curr_df["2ndFlrSF"] - train_df["2ndFlrSF"].mean()) / train_df["2ndFlrSF"].std()
    curr_df["LowQualFinSF"] = (curr_df["LowQualFinSF"] - train_df["LowQualFinSF"].mean()) / train_df["LowQualFinSF"].std()
    curr_df["GrLivArea"] = (curr_df["GrLivArea"] - train_df["GrLivArea"].mean()) / train_df["GrLivArea"].std()
    curr_df["BsmtFullBath"] = (curr_df["BsmtFullBath"] - train_df["BsmtFullBath"].mean()) / train_df["BsmtFullBath"].std()
    curr_df["BsmtHalfBath"] = (curr_df["BsmtHalfBath"] - train_df["BsmtHalfBath"].mean()) / train_df["BsmtHalfBath"].std()
    curr_df["FullBath"] = (curr_df["FullBath"] - train_df["FullBath"].mean()) / train_df["FullBath"].std()
    curr_df["HalfBath"] = (curr_df["HalfBath"] - train_df["HalfBath"].mean()) / train_df["HalfBath"].std()
    curr_df["BedroomAbvGr"] = (curr_df["BedroomAbvGr"] - train_df["BedroomAbvGr"].mean()) / train_df["BedroomAbvGr"].std()
    curr_df["KitchenAbvGr"] = (curr_df["KitchenAbvGr"] - train_df["KitchenAbvGr"].mean()) / train_df["KitchenAbvGr"].std()
    curr_df["TotRmsAbvGrd"] = (curr_df["TotRmsAbvGrd"] - train_df["TotRmsAbvGrd"].mean()) / train_df["TotRmsAbvGrd"].std()
    curr_df["Fireplaces"] = (curr_df["Fireplaces"] - train_df["Fireplaces"].mean()) / train_df["Fireplaces"].std()
    curr_df["GarageYrBlt"] = (curr_df["GarageYrBlt"] - train_df["GarageYrBlt"].mean()) / train_df["GarageYrBlt"].std()
    curr_df["GarageCars"] = (curr_df["GarageCars"] - train_df["GarageCars"].mean()) / train_df["GarageCars"].std()
    curr_df["GarageArea"] = (curr_df["GarageArea"] - train_df["GarageArea"].mean()) / train_df["GarageArea"].std()
    curr_df["WoodDeckSF"] = (curr_df["WoodDeckSF"] - train_df["WoodDeckSF"].mean()) / train_df["WoodDeckSF"].std()
    curr_df["OpenPorchSF"] = (curr_df["OpenPorchSF"] - train_df["OpenPorchSF"].mean()) / train_df["OpenPorchSF"].std()
    curr_df["EnclosedPorch"] = (curr_df["EnclosedPorch"] - train_df["EnclosedPorch"].mean()) / train_df["EnclosedPorch"].std()
    curr_df["3SsnPorch"] = (curr_df["3SsnPorch"] - train_df["3SsnPorch"].mean()) / train_df["3SsnPorch"].std()
    curr_df["ScreenPorch"] = (curr_df["ScreenPorch"] - train_df["ScreenPorch"].mean()) / train_df["ScreenPorch"].std()
    curr_df["PoolArea"] = (curr_df["PoolArea"] - train_df["PoolArea"].mean()) / train_df["PoolArea"].std()
    curr_df["MiscVal"] = (curr_df["MiscVal"] - train_df["MiscVal"].mean()) / train_df["MiscVal"].std()

    return curr_df

In [404]:
# tr_df_2 = trans_features(tr_df)

# tr_df_2

In [405]:
oh_columns = [
    "MSSubClass", "MSZoning",
    "LotConfig", "Neighborhood", "Condition1", "Condition2", "BldgType",
    "HouseStyle",  "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd", "MasVnrType",
    "Foundation", "Heating", "Electrical", "GarageType", "GarageFinish", "Fence", "MiscFeature",
    "SaleType", "SaleCondition"
]
# asis_columns = [
#     "LotFrontage", "LotArea", "OverallQual", "OverallCond", "YearRemodAdd", "MasVnrArea",
#     "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF",
#     "LowQualFinSF", "GrLivArea", "BsmtFullBath", "BsmtHalfBath", "FullBath", "HalfBath",
#     "Bedroom", "Kitchen", "TotRmsAbvGrd", "Fireplaces", "GarageCars",
#     "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch",
#     "PoolArea", "MiscVal", "GarageYrBlt"
# ]
# already_processed = ["Street", "CentralAir", "PavedDrive"]
# dropped_columns = ["YearBuilt", "MoSold", "YrSold", "SaleType", "SaleCondition", "GarageYrBlt"]
dropped_columns = []

In [406]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

def encode_features(train_df, curr_df, oh_columns):
    encoder.fit_transform(train_df[oh_columns]),
    encoded_data = pd.DataFrame(
        encoder.transform(curr_df[oh_columns]),
        columns=encoder.get_feature_names_out(oh_columns),
        index=curr_df.index
    )
    curr_df.drop(columns=oh_columns, inplace=True)
    curr_df = pd.concat([curr_df, encoded_data], axis=1)
    return curr_df

In [407]:
# tr_df_2 = tr_df_2.drop(columns=dropped_columns)

In [408]:
raw_features = tr_df.drop(columns=["SalePrice"])
targets = tr_df["SalePrice"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    raw_features,
    targets,
    random_state=42,
    shuffle=True,
    train_size=0.7
)

In [409]:
# from sklearn.preprocessing import OneHotEncoder
# encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
# encoded_data = pd.DataFrame(
#     encoder.fit_transform(X_train[oh_columns]),
#     columns=encoder.get_feature_names_out(oh_columns),
#     index=X_train.index
# )
# X_train.drop(columns=oh_columns, inplace=True)
# X_train = pd.concat([X_train, encoded_data], axis=1)
# X_train

In [410]:
# encoded_test_split_data = pd.DataFrame(
#     encoder.transform(X_test[oh_columns]),
#     columns=encoder.get_feature_names_out(oh_columns),
#     index=X_test.index
# )
# X_test.drop(columns=oh_columns, inplace=True)
# X_test = pd.concat([X_test, encoded_test_split_data], axis=1)
# X_test

In [411]:
# X_test.info(verbose=True, show_counts=True)
# # X_train.info(verbose=True, show_counts=True)

In [412]:
# tr_df.info()

In [413]:
# tr_df["YearRemodAdd"]

In [414]:
# tr_df["Alley"].unique()

In [415]:
# train_data = tr_df.drop(columns=["SalePrice"])
# train_data

In [416]:
# tr_df.columns

In [417]:
# from sklearn.preprocessing import OneHotEncoder

# encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
# encoded_data = encoder.fit_transform(tr_df[tr_df.columns])
# print(encoded_data.shape)

In [418]:
# tr_df[["MSZoning", "Alley"]]

In [419]:
# test_data = tr_df["SalePrice"]
# test_data

In [420]:
# len(tr_df.columns)

In [421]:
X_train = trans_features(X_train)
X_train = normalize_features(X_train, X_train)
X_train = encode_features(X_train, X_train, oh_columns)

X_test = trans_features(X_test)
X_test = normalize_features(X_train, X_test)
X_test = encode_features(X_test, X_test, oh_columns)

TypeError: 'NoneType' object is not subscriptable

In [350]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=50,
    random_state=42
)

In [351]:
from sklearn.metrics import root_mean_squared_error

rf.fit(X_train, y_train)
training_predictions = rf.predict(X_train)
root_mean_squared_error(y_true=y_train, y_pred=training_predictions)

11751.012627196451

In [352]:
testing_split_predictions = rf.predict(X_test)
root_mean_squared_error(y_true=y_test, y_pred=testing_split_predictions)

26835.227801261623

In [353]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators = 10,
    num_parallel_tree = 50,
    max_depth = 50,
    random_state = 42
)

In [354]:
xgb.fit(X_train, y_train)
training_predictions = xgb.predict(X_train)
root_mean_squared_error(y_true=y_train, y_pred=training_predictions)

6085.07080078125

In [355]:
testing_split_predictions = xgb.predict(X_test)
root_mean_squared_error(y_true=y_test, y_pred=testing_split_predictions)

30523.4453125

In [356]:
X_train.info(show_counts=True, verbose=True)

<class 'pandas.DataFrame'>
Index: 1021 entries, 1453 to 1127
Data columns (total 235 columns):
 #    Column                 Non-Null Count  Dtype
---   ------                 --------------  -----
 0    LotFrontage            1021 non-null   float64
 1    LotArea                1021 non-null   int64
 2    Street                 1021 non-null   int64
 3    Alley                  1021 non-null   int64
 4    LotShape               1021 non-null   int64
 5    LandContour            1021 non-null   int64
 6    Utilities              1021 non-null   int64
 7    LandSlope              1021 non-null   int64
 8    OverallQual            1021 non-null   int64
 9    OverallCond            1021 non-null   int64
 10   YearBuilt              1021 non-null   int64
 11   YearRemodAdd           1021 non-null   int64
 12   MasVnrArea             1021 non-null   float64
 13   ExterQual              1021 non-null   int64
 14   ExterCond              1021 non-null   int64
 15   BsmtQual               1021 non-null   int64
 16   BsmtCond               1021 non-null   int64
 17   BsmtExposure           1021 non-null   int64
 18   BsmtFinType1           1021 non-null   int64
 19   BsmtFinSF1             1021 non-null   int64
 20   BsmtFinType2           1021 non-null   int64
 21   BsmtFinSF2             1021 non-null   int64
 22   BsmtUnfSF              1021 non-null   int64
 23   TotalBsmtSF            1021 non-null   int64
 24   HeatingQC              1021 non-null   int64
 25   CentralAir             1021 non-null   int64
 26   1stFlrSF               1021 non-null   int64
 27   2ndFlrSF               1021 non-null   int64
 28   LowQualFinSF           1021 non-null   int64
 29   GrLivArea              1021 non-null   int64
 30   BsmtFullBath           1021 non-null   int64
 31   BsmtHalfBath           1021 non-null   int64
 32   FullBath               1021 non-null   int64
 33   HalfBath               1021 non-null   int64
 34   BedroomAbvGr           1021 non-null   int64
 35   KitchenAbvGr           1021 non-null   int64
 36   KitchenQual            1021 non-null   int64
 37   TotRmsAbvGrd           1021 non-null   int64
 38   Functional             1021 non-null   int64
 39   Fireplaces             1021 non-null   int64
 40   FireplaceQu            1021 non-null   int64
 41   GarageYrBlt            1021 non-null   float64
 42   GarageCars             1021 non-null   int64
 43   GarageArea             1021 non-null   int64
 44   GarageQual             1021 non-null   int64
 45   GarageCond             1021 non-null   int64
 46   PavedDrive             1021 non-null   int64
 47   WoodDeckSF             1021 non-null   int64
 48   OpenPorchSF            1021 non-null   int64
 49   EnclosedPorch          1021 non-null   int64
 50   3SsnPorch              1021 non-null   int64
 51   ScreenPorch            1021 non-null   int64
 52   PoolArea               1021 non-null   int64
 53   PoolQC                 1021 non-null   int64
 54   MiscVal                1021 non-null   int64
 55   MoSold                 1021 non-null   int64
 56   YrSold                 1021 non-null   int64
 57   MSSubClass_20          1021 non-null   float64
 58   MSSubClass_30          1021 non-null   float64
 59   MSSubClass_40          1021 non-null   float64
 60   MSSubClass_45          1021 non-null   float64
 61   MSSubClass_50          1021 non-null   float64
 62   MSSubClass_60          1021 non-null   float64
 63   MSSubClass_70          1021 non-null   float64
 64   MSSubClass_75          1021 non-null   float64
 65   MSSubClass_80          1021 non-null   float64
 66   MSSubClass_85          1021 non-null   float64
 67   MSSubClass_90          1021 non-null   float64
 68   MSSubClass_120         1021 non-null   float64
 69   MSSubClass_160         1021 non-null   float64
 70   MSSubClass_180         1021 non-null   float64
 71   MSSubClass_190         1021 non-null   float64
 72   MSZoning_C (all)       1021 non-null   float64
 73   MSZoning_FV            1021 non-null   float64
 74   MSZoning_RH            1021 non-null   float64
 75   MSZoning_RL            1021 non-null   float64
 76   MSZoning_RM            1021 non-null   float64
 77   LotConfig_Corner       1021 non-null   float64
 78   LotConfig_CulDSac      1021 non-null   float64
 79   LotConfig_FR2          1021 non-null   float64
 80   LotConfig_FR3          1021 non-null   float64
 81   LotConfig_Inside       1021 non-null   float64
 82   Neighborhood_Blmngtn   1021 non-null   float64
 83   Neighborhood_Blueste   1021 non-null   float64
 84   Neighborhood_BrDale    1021 non-null   float64
 85   Neighborhood_BrkSide   1021 non-null   float64
 86   Neighborhood_ClearCr   1021 non-null   float64
 87   Neighborhood_CollgCr   1021 non-null   float64
 88   Neighborhood_Crawfor   1021 non-null   float64
 89   Neighborhood_Edwards   1021 non-null   float64
 90   Neighborhood_Gilbert   1021 non-null   float64
 91   Neighborhood_IDOTRR    1021 non-null   float64
 92   Neighborhood_MeadowV   1021 non-null   float64
 93   Neighborhood_Mitchel   1021 non-null   float64
 94   Neighborhood_NAmes     1021 non-null   float64
 95   Neighborhood_NPkVill   1021 non-null   float64
 96   Neighborhood_NWAmes    1021 non-null   float64
 97   Neighborhood_NoRidge   1021 non-null   float64
 98   Neighborhood_NridgHt   1021 non-null   float64
 99   Neighborhood_OldTown   1021 non-null   float64
 100  Neighborhood_SWISU     1021 non-null   float64
 101  Neighborhood_Sawyer    1021 non-null   float64
 102  Neighborhood_SawyerW   1021 non-null   float64
 103  Neighborhood_Somerst   1021 non-null   float64
 104  Neighborhood_StoneBr   1021 non-null   float64
 105  Neighborhood_Timber    1021 non-null   float64
 106  Neighborhood_Veenker   1021 non-null   float64
 107  Condition1_Artery      1021 non-null   float64
 108  Condition1_Feedr       1021 non-null   float64
 109  Condition1_Norm        1021 non-null   float64
 110  Condition1_PosA        1021 non-null   float64
 111  Condition1_PosN        1021 non-null   float64
 112  Condition1_RRAe        1021 non-null   float64
 113  Condition1_RRAn        1021 non-null   float64
 114  Condition1_RRNe        1021 non-null   float64
 115  Condition1_RRNn        1021 non-null   float64
 116  Condition2_Artery      1021 non-null   float64
 117  Condition2_Feedr       1021 non-null   float64
 118  Condition2_Norm        1021 non-null   float64
 119  Condition2_PosN        1021 non-null   float64
 120  Condition2_RRAe        1021 non-null   float64
 121  Condition2_RRAn        1021 non-null   float64
 122  BldgType_1Fam          1021 non-null   float64
 123  BldgType_2fmCon        1021 non-null   float64
 124  BldgType_Duplex        1021 non-null   float64
 125  BldgType_Twnhs         1021 non-null   float64
 126  BldgType_TwnhsE        1021 non-null   float64
 127  HouseStyle_1.5Fin      1021 non-null   float64
 128  HouseStyle_1.5Unf      1021 non-null   float64
 129  HouseStyle_1Story      1021 non-null   float64
 130  HouseStyle_2.5Fin      1021 non-null   float64
 131  HouseStyle_2.5Unf      1021 non-null   float64
 132  HouseStyle_2Story      1021 non-null   float64
 133  HouseStyle_SFoyer      1021 non-null   float64
 134  HouseStyle_SLvl        1021 non-null   float64
 135  RoofStyle_Flat         1021 non-null   float64
 136  RoofStyle_Gable        1021 non-null   float64
 137  RoofStyle_Gambrel      1021 non-null   float64
 138  RoofStyle_Hip          1021 non-null   float64
 139  RoofStyle_Mansard      1021 non-null   float64
 140  RoofStyle_Shed         1021 non-null   float64
 141  RoofMatl_ClyTile       1021 non-null   float64
 142  RoofMatl_CompShg       1021 non-null   float64
 143  RoofMatl_Metal         1021 non-null   float64
 144  RoofMatl_Roll          1021 non-null   float64
 145  RoofMatl_Tar&Grv       1021 non-null   float64
 146  RoofMatl_WdShake       1021 non-null   float64
 147  RoofMatl_WdShngl       1021 non-null   float64
 148  Exterior1st_AsbShng    1021 non-null   float64
 149  Exterior1st_AsphShn    1021 non-null   float64
 150  Exterior1st_BrkComm    1021 non-null   float64
 151  Exterior1st_BrkFace    1021 non-null   float64
 152  Exterior1st_CBlock     1021 non-null   float64
 153  Exterior1st_CemntBd    1021 non-null   float64
 154  Exterior1st_HdBoard    1021 non-null   float64
 155  Exterior1st_MetalSd    1021 non-null   float64
 156  Exterior1st_Plywood    1021 non-null   float64
 157  Exterior1st_Stone      1021 non-null   float64
 158  Exterior1st_Stucco     1021 non-null   float64
 159  Exterior1st_VinylSd    1021 non-null   float64
 160  Exterior1st_Wd Sdng    1021 non-null   float64
 161  Exterior1st_WdShing    1021 non-null   float64
 162  Exterior2nd_AsbShng    1021 non-null   float64
 163  Exterior2nd_AsphShn    1021 non-null   float64
 164  Exterior2nd_Brk Cmn    1021 non-null   float64
 165  Exterior2nd_BrkFace    1021 non-null   float64
 166  Exterior2nd_CBlock     1021 non-null   float64
 167  Exterior2nd_CmentBd    1021 non-null   float64
 168  Exterior2nd_HdBoard    1021 non-null   float64
 169  Exterior2nd_ImStucc    1021 non-null   float64
 170  Exterior2nd_MetalSd    1021 non-null   float64
 171  Exterior2nd_Other      1021 non-null   float64
 172  Exterior2nd_Plywood    1021 non-null   float64
 173  Exterior2nd_Stone      1021 non-null   float64
 174  Exterior2nd_Stucco     1021 non-null   float64
 175  Exterior2nd_VinylSd    1021 non-null   float64
 176  Exterior2nd_Wd Sdng    1021 non-null   float64
 177  Exterior2nd_Wd Shng    1021 non-null   float64
 178  MasVnrType_BrkCmn      1021 non-null   float64
 179  MasVnrType_BrkFace     1021 non-null   float64
 180  MasVnrType_Stone       1021 non-null   float64
 181  MasVnrType_nan         1021 non-null   float64
 182  Foundation_BrkTil      1021 non-null   float64
 183  Foundation_CBlock      1021 non-null   float64
 184  Foundation_PConc       1021 non-null   float64
 185  Foundation_Slab        1021 non-null   float64
 186  Foundation_Stone       1021 non-null   float64
 187  Foundation_Wood        1021 non-null   float64
 188  Heating_Floor          1021 non-null   float64
 189  Heating_GasA           1021 non-null   float64
 190  Heating_GasW           1021 non-null   float64
 191  Heating_Grav           1021 non-null   float64
 192  Heating_OthW           1021 non-null   float64
 193  Heating_Wall           1021 non-null   float64
 194  Electrical_FuseA       1021 non-null   float64
 195  Electrical_FuseF       1021 non-null   float64
 196  Electrical_FuseP       1021 non-null   float64
 197  Electrical_SBrkr       1021 non-null   float64
 198  Electrical_nan         1021 non-null   float64
 199  GarageType_2Types      1021 non-null   float64
 200  GarageType_Attchd      1021 non-null   float64
 201  GarageType_Basment     1021 non-null   float64
 202  GarageType_BuiltIn     1021 non-null   float64
 203  GarageType_CarPort     1021 non-null   float64
 204  GarageType_Detchd      1021 non-null   float64
 205  GarageType_nan         1021 non-null   float64
 206  GarageFinish_Fin       1021 non-null   float64
 207  GarageFinish_RFn       1021 non-null   float64
 208  GarageFinish_Unf       1021 non-null   float64
 209  GarageFinish_nan       1021 non-null   float64
 210  Fence_GdPrv            1021 non-null   float64
 211  Fence_GdWo             1021 non-null   float64
 212  Fence_MnPrv            1021 non-null   float64
 213  Fence_MnWw             1021 non-null   float64
 214  Fence_nan              1021 non-null   float64
 215  MiscFeature_Gar2       1021 non-null   float64
 216  MiscFeature_Othr       1021 non-null   float64
 217  MiscFeature_Shed       1021 non-null   float64
 218  MiscFeature_TenC       1021 non-null   float64
 219  MiscFeature_nan        1021 non-null   float64
 220  SaleType_COD           1021 non-null   float64
 221  SaleType_CWD           1021 non-null   float64
 222  SaleType_Con           1021 non-null   float64
 223  SaleType_ConLD         1021 non-null   float64
 224  SaleType_ConLI         1021 non-null   float64
 225  SaleType_ConLw         1021 non-null   float64
 226  SaleType_New           1021 non-null   float64
 227  SaleType_Oth           1021 non-null   float64
 228  SaleType_WD            1021 non-null   float64
 229  SaleCondition_Abnorml  1021 non-null   float64
 230  SaleCondition_AdjLand  1021 non-null   float64
 231  SaleCondition_Alloca   1021 non-null   float64
 232  SaleCondition_Family   1021 non-null   float64
 233  SaleCondition_Normal   1021 non-null   float64
 234  SaleCondition_Partial  1021 non-null   float64
dtypes: float64(181), int64(54)
memory usage: 1.8 MB

In [357]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
training_predictions = lr.predict(X_train)
root_mean_squared_error(y_true=y_train, y_pred=training_predictions)

21625.93302068043

In [358]:
testing_split_predictions = lr.predict(X_test)
root_mean_squared_error(y_true=y_test, y_pred=testing_split_predictions)

28894.386227793722

In [197]:
test_data = pd.read_csv("./home-data-for-ml-course/test.csv", index_col="Id")
test_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [198]:
test_df_2 = test_data.copy()
test_df_2["Street"] = test_data["Street"].map({"Grvl": 0, "Pave": 1}).astype("int64")
test_df_2["Alley"] = test_data["Alley"].map({"Grvl": 1, "Pave": 2}).fillna(0).astype("int64")
test_df_2["LotShape"] = test_data["LotShape"].map({"Reg": 3, "IR1": 2, "IR2": 1, "IR3": 0}).astype("int64")
test_df_2["LandContour"] = test_data["LandContour"].map({"Lvl": 3, "Bnk": 2, "HLS": 1, "Low": 0}).astype("int64")
test_df_2["Utilities"] = test_data["Utilities"].map({"AllPub": 3, "NoSewr": 2, "NoSeWa": 1, "ELO": 0}).fillna(0).astype("int64")
test_df_2["LandSlope"] = test_data["LandSlope"].map({"Gtl": 2, "Mod": 1, "Sev": 0}).astype("int64")
test_df_2["ExterQual"] = test_data["ExterQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
test_df_2["ExterCond"] = test_data["ExterCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
test_df_2["BsmtQual"] = test_data["BsmtQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["BsmtCond"] = test_data["BsmtCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["BsmtExposure"] = test_data["BsmtExposure"].map({"Gd": 4, "Av": 3, "Mn": 2, "No": 1}).fillna(0).astype("int64")
test_df_2["BsmtFinType1"] = test_data["BsmtFinType1"].map({"GLQ": 6, "ALQ": 5, "BLQ": 4, "Rec": 3, "LwQ": 2, "Unf": 1}).fillna(0).astype("int64")
test_df_2["BsmtFinType2"] = test_data["BsmtFinType2"].map({"GLQ": 6, "ALQ": 5, "BLQ": 4, "Rec": 3, "LwQ": 2, "Unf": 1}).fillna(0).astype("int64")
test_df_2["HeatingQC"] = test_data["HeatingQC"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).astype("int64")
test_df_2["CentralAir"] = test_data["CentralAir"].map({"N": 0, "Y": 1}).astype("int64")
test_df_2["KitchenQual"] = test_data["KitchenQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["Functional"] = test_data["Functional"].map({"Typ": 8, "Min1": 7, "Min2": 6, "Mod": 5, "Maj1": 4, "Maj2": 3, "Sev": 2, "Sal": 1}).fillna(0).astype("int64")
test_df_2["FireplaceQu"] = test_data["FireplaceQu"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["GarageQual"] = test_data["GarageQual"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["GarageCond"] = test_data["GarageCond"].map({"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}).fillna(0).astype("int64")
test_df_2["PavedDrive"] = test_data["PavedDrive"].map({"Y": 2, "P": 1, "N": 0}).astype("int64")
test_df_2["PoolQC"] = test_data["PoolQC"].map({"Ex": 4, "Gd": 3, "TA": 2, "Fa": 1,}).fillna(0).astype("int64")

test_df_2["LotFrontage"] = test_data["LotFrontage"].fillna(0)
test_df_2["MasVnrArea"] = test_data["MasVnrArea"].fillna(0)
test_df_2["BsmtFinSF1"] = test_data["BsmtFinSF1"].fillna(0)
test_df_2["BsmtFinSF2"] = test_data["BsmtFinSF2"].fillna(0)
test_df_2["BsmtUnfSF"] = test_data["BsmtUnfSF"].fillna(0)
test_df_2["TotalBsmtSF"] = test_data["TotalBsmtSF"].fillna(0)
test_df_2["BsmtFullBath"] = test_data["BsmtFullBath"].fillna(0)
test_df_2["BsmtHalfBath"] = test_data["BsmtHalfBath"].fillna(0)
test_df_2["GarageCars"] = test_data["GarageCars"].fillna(0)
test_df_2["GarageArea"] = test_data["GarageArea"].fillna(0)


test_df_2 = test_df_2.drop(columns=dropped_columns)
test_df_2

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,1,0,3,3,3,Inside,...,140,0,0,0,120,0,0,MnPrv,NaN,0
1462,20,RL,81.0,14267,1,0,2,3,3,Corner,...,393,36,0,0,0,0,0,NaN,Gar2,12500
1463,60,RL,74.0,13830,1,0,2,3,3,Inside,...,212,34,0,0,0,0,0,MnPrv,NaN,0
1464,60,RL,78.0,9978,1,0,2,3,3,Inside,...,360,36,0,0,0,0,0,NaN,NaN,0
1465,120,RL,43.0,5005,1,0,2,1,3,Inside,...,0,82,0,0,144,0,0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,1,0,3,3,3,Inside,...,0,0,0,0,0,0,0,NaN,NaN,0
2916,160,RM,21.0,1894,1,0,3,3,3,Inside,...,0,24,0,0,0,0,0,NaN,NaN,0
2917,20,RL,160.0,20000,1,0,3,3,3,Inside,...,474,0,0,0,0,0,0,NaN,NaN,0
2918,85,RL,62.0,10441,1,0,3,3,3,Inside,...,80,32,0,0,0,0,0,MnPrv,Shed,700
2919,60,RL,74.0,9627,1,0,3,3,3,Inside,...,190,48,0,0,0,0,0,NaN,NaN,0

In [199]:
encoded_data = pd.DataFrame(
    encoder.transform(test_df_2[oh_columns]),
    columns=encoder.get_feature_names_out(oh_columns),
    index=test_df_2.index
)
test_df_2.drop(columns=oh_columns, inplace=True)
test_df_2 = pd.concat([test_df_2, encoded_data], axis=1)
test_df_2

,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LandSlope,OverallQual,OverallCond,...,Fence_GdPrv,Fence_GdWo,Fence_MnPrv,Fence_MnWw,Fence_nan,MiscFeature_Gar2,MiscFeature_Othr,MiscFeature_Shed,MiscFeature_TenC,MiscFeature_nan
Id,,,,,,,,,,,,,,,,,,,,,
1461,80.0,11622,1,0,3,3,3,2,5,6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1462,81.0,14267,1,0,2,3,3,2,6,6,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1463,74.0,13830,1,0,2,3,3,2,5,5,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1464,78.0,9978,1,0,2,3,3,2,6,6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1465,43.0,5005,1,0,2,1,3,2,8,5,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,21.0,1936,1,0,3,3,3,2,4,7,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2916,21.0,1894,1,0,3,3,3,2,4,5,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2917,160.0,20000,1,0,3,3,3,2,5,7,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2918,62.0,10441,1,0,3,3,3,2,5,5,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2919,74.0,9627,1,0,3,3,3,1,7,5,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [200]:
test_df_2.info(show_counts=True, verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 1461 to 2919
Data columns (total 216 columns):
 #    Column                Non-Null Count  Dtype
---   ------                --------------  -----
 0    LotFrontage           1459 non-null   float64
 1    LotArea               1459 non-null   int64
 2    Street                1459 non-null   int64
 3    Alley                 1459 non-null   int64
 4    LotShape              1459 non-null   int64
 5    LandContour           1459 non-null   int64
 6    Utilities             1459 non-null   int64
 7    LandSlope             1459 non-null   int64
 8    OverallQual           1459 non-null   int64
 9    OverallCond           1459 non-null   int64
 10   YearRemodAdd          1459 non-null   int64
 11   MasVnrArea            1459 non-null   float64
 12   ExterQual             1459 non-null   int64
 13   ExterCond             1459 non-null   int64
 14   BsmtQual              1459 non-null   int64
 15   BsmtCond              1459 non-null   int64
 16   BsmtExposure          1459 non-null   int64
 17   BsmtFinType1          1459 non-null   int64
 18   BsmtFinSF1            1459 non-null   float64
 19   BsmtFinType2          1459 non-null   int64
 20   BsmtFinSF2            1459 non-null   float64
 21   BsmtUnfSF             1459 non-null   float64
 22   TotalBsmtSF           1459 non-null   float64
 23   HeatingQC             1459 non-null   int64
 24   CentralAir            1459 non-null   int64
 25   1stFlrSF              1459 non-null   int64
 26   2ndFlrSF              1459 non-null   int64
 27   LowQualFinSF          1459 non-null   int64
 28   GrLivArea             1459 non-null   int64
 29   BsmtFullBath          1459 non-null   float64
 30   BsmtHalfBath          1459 non-null   float64
 31   FullBath              1459 non-null   int64
 32   HalfBath              1459 non-null   int64
 33   BedroomAbvGr          1459 non-null   int64
 34   KitchenAbvGr          1459 non-null   int64
 35   KitchenQual           1459 non-null   int64
 36   TotRmsAbvGrd          1459 non-null   int64
 37   Functional            1459 non-null   int64
 38   Fireplaces            1459 non-null   int64
 39   FireplaceQu           1459 non-null   int64
 40   GarageCars            1459 non-null   float64
 41   GarageArea            1459 non-null   float64
 42   GarageQual            1459 non-null   int64
 43   GarageCond            1459 non-null   int64
 44   PavedDrive            1459 non-null   int64
 45   WoodDeckSF            1459 non-null   int64
 46   OpenPorchSF           1459 non-null   int64
 47   EnclosedPorch         1459 non-null   int64
 48   3SsnPorch             1459 non-null   int64
 49   ScreenPorch           1459 non-null   int64
 50   PoolArea              1459 non-null   int64
 51   PoolQC                1459 non-null   int64
 52   MiscVal               1459 non-null   int64
 53   MSSubClass_20         1459 non-null   float64
 54   MSSubClass_30         1459 non-null   float64
 55   MSSubClass_40         1459 non-null   float64
 56   MSSubClass_45         1459 non-null   float64
 57   MSSubClass_50         1459 non-null   float64
 58   MSSubClass_60         1459 non-null   float64
 59   MSSubClass_70         1459 non-null   float64
 60   MSSubClass_75         1459 non-null   float64
 61   MSSubClass_80         1459 non-null   float64
 62   MSSubClass_85         1459 non-null   float64
 63   MSSubClass_90         1459 non-null   float64
 64   MSSubClass_120        1459 non-null   float64
 65   MSSubClass_160        1459 non-null   float64
 66   MSSubClass_180        1459 non-null   float64
 67   MSSubClass_190        1459 non-null   float64
 68   MSZoning_C (all)      1459 non-null   float64
 69   MSZoning_FV           1459 non-null   float64
 70   MSZoning_RH           1459 non-null   float64
 71   MSZoning_RL           1459 non-null   float64
 72   MSZoning_RM           1459 non-null   float64
 73   LotConfig_Corner      1459 non-null   float64
 74   LotConfig_CulDSac     1459 non-null   float64
 75   LotConfig_FR2         1459 non-null   float64
 76   LotConfig_FR3         1459 non-null   float64
 77   LotConfig_Inside      1459 non-null   float64
 78   Neighborhood_Blmngtn  1459 non-null   float64
 79   Neighborhood_Blueste  1459 non-null   float64
 80   Neighborhood_BrDale   1459 non-null   float64
 81   Neighborhood_BrkSide  1459 non-null   float64
 82   Neighborhood_ClearCr  1459 non-null   float64
 83   Neighborhood_CollgCr  1459 non-null   float64
 84   Neighborhood_Crawfor  1459 non-null   float64
 85   Neighborhood_Edwards  1459 non-null   float64
 86   Neighborhood_Gilbert  1459 non-null   float64
 87   Neighborhood_IDOTRR   1459 non-null   float64
 88   Neighborhood_MeadowV  1459 non-null   float64
 89   Neighborhood_Mitchel  1459 non-null   float64
 90   Neighborhood_NAmes    1459 non-null   float64
 91   Neighborhood_NPkVill  1459 non-null   float64
 92   Neighborhood_NWAmes   1459 non-null   float64
 93   Neighborhood_NoRidge  1459 non-null   float64
 94   Neighborhood_NridgHt  1459 non-null   float64
 95   Neighborhood_OldTown  1459 non-null   float64
 96   Neighborhood_SWISU    1459 non-null   float64
 97   Neighborhood_Sawyer   1459 non-null   float64
 98   Neighborhood_SawyerW  1459 non-null   float64
 99   Neighborhood_Somerst  1459 non-null   float64
 100  Neighborhood_StoneBr  1459 non-null   float64
 101  Neighborhood_Timber   1459 non-null   float64
 102  Neighborhood_Veenker  1459 non-null   float64
 103  Condition1_Artery     1459 non-null   float64
 104  Condition1_Feedr      1459 non-null   float64
 105  Condition1_Norm       1459 non-null   float64
 106  Condition1_PosA       1459 non-null   float64
 107  Condition1_PosN       1459 non-null   float64
 108  Condition1_RRAe       1459 non-null   float64
 109  Condition1_RRAn       1459 non-null   float64
 110  Condition1_RRNe       1459 non-null   float64
 111  Condition1_RRNn       1459 non-null   float64
 112  Condition2_Artery     1459 non-null   float64
 113  Condition2_Feedr      1459 non-null   float64
 114  Condition2_Norm       1459 non-null   float64
 115  Condition2_PosN       1459 non-null   float64
 116  Condition2_RRAe       1459 non-null   float64
 117  Condition2_RRAn       1459 non-null   float64
 118  BldgType_1Fam         1459 non-null   float64
 119  BldgType_2fmCon       1459 non-null   float64
 120  BldgType_Duplex       1459 non-null   float64
 121  BldgType_Twnhs        1459 non-null   float64
 122  BldgType_TwnhsE       1459 non-null   float64
 123  HouseStyle_1.5Fin     1459 non-null   float64
 124  HouseStyle_1.5Unf     1459 non-null   float64
 125  HouseStyle_1Story     1459 non-null   float64
 126  HouseStyle_2.5Fin     1459 non-null   float64
 127  HouseStyle_2.5Unf     1459 non-null   float64
 128  HouseStyle_2Story     1459 non-null   float64
 129  HouseStyle_SFoyer     1459 non-null   float64
 130  HouseStyle_SLvl       1459 non-null   float64
 131  RoofStyle_Flat        1459 non-null   float64
 132  RoofStyle_Gable       1459 non-null   float64
 133  RoofStyle_Gambrel     1459 non-null   float64
 134  RoofStyle_Hip         1459 non-null   float64
 135  RoofStyle_Mansard     1459 non-null   float64
 136  RoofStyle_Shed        1459 non-null   float64
 137  RoofMatl_ClyTile      1459 non-null   float64
 138  RoofMatl_CompShg      1459 non-null   float64
 139  RoofMatl_Metal        1459 non-null   float64
 140  RoofMatl_Roll         1459 non-null   float64
 141  RoofMatl_Tar&Grv      1459 non-null   float64
 142  RoofMatl_WdShake      1459 non-null   float64
 143  RoofMatl_WdShngl      1459 non-null   float64
 144  Exterior1st_AsbShng   1459 non-null   float64
 145  Exterior1st_AsphShn   1459 non-null   float64
 146  Exterior1st_BrkComm   1459 non-null   float64
 147  Exterior1st_BrkFace   1459 non-null   float64
 148  Exterior1st_CBlock    1459 non-null   float64
 149  Exterior1st_CemntBd   1459 non-null   float64
 150  Exterior1st_HdBoard   1459 non-null   float64
 151  Exterior1st_MetalSd   1459 non-null   float64
 152  Exterior1st_Plywood   1459 non-null   float64
 153  Exterior1st_Stone     1459 non-null   float64
 154  Exterior1st_Stucco    1459 non-null   float64
 155  Exterior1st_VinylSd   1459 non-null   float64
 156  Exterior1st_Wd Sdng   1459 non-null   float64
 157  Exterior1st_WdShing   1459 non-null   float64
 158  Exterior2nd_AsbShng   1459 non-null   float64
 159  Exterior2nd_AsphShn   1459 non-null   float64
 160  Exterior2nd_Brk Cmn   1459 non-null   float64
 161  Exterior2nd_BrkFace   1459 non-null   float64
 162  Exterior2nd_CBlock    1459 non-null   float64
 163  Exterior2nd_CmentBd   1459 non-null   float64
 164  Exterior2nd_HdBoard   1459 non-null   float64
 165  Exterior2nd_ImStucc   1459 non-null   float64
 166  Exterior2nd_MetalSd   1459 non-null   float64
 167  Exterior2nd_Other     1459 non-null   float64
 168  Exterior2nd_Plywood   1459 non-null   float64
 169  Exterior2nd_Stone     1459 non-null   float64
 170  Exterior2nd_Stucco    1459 non-null   float64
 171  Exterior2nd_VinylSd   1459 non-null   float64
 172  Exterior2nd_Wd Sdng   1459 non-null   float64
 173  Exterior2nd_Wd Shng   1459 non-null   float64
 174  MasVnrType_BrkCmn     1459 non-null   float64
 175  MasVnrType_BrkFace    1459 non-null   float64
 176  MasVnrType_Stone      1459 non-null   float64
 177  MasVnrType_nan        1459 non-null   float64
 178  Foundation_BrkTil     1459 non-null   float64
 179  Foundation_CBlock     1459 non-null   float64
 180  Foundation_PConc      1459 non-null   float64
 181  Foundation_Slab       1459 non-null   float64
 182  Foundation_Stone      1459 non-null   float64
 183  Foundation_Wood       1459 non-null   float64
 184  Heating_Floor         1459 non-null   float64
 185  Heating_GasA          1459 non-null   float64
 186  Heating_GasW          1459 non-null   float64
 187  Heating_Grav          1459 non-null   float64
 188  Heating_OthW          1459 non-null   float64
 189  Heating_Wall          1459 non-null   float64
 190  Electrical_FuseA      1459 non-null   float64
 191  Electrical_FuseF      1459 non-null   float64
 192  Electrical_FuseP      1459 non-null   float64
 193  Electrical_SBrkr      1459 non-null   float64
 194  Electrical_nan        1459 non-null   float64
 195  GarageType_2Types     1459 non-null   float64
 196  GarageType_Attchd     1459 non-null   float64
 197  GarageType_Basment    1459 non-null   float64
 198  GarageType_BuiltIn    1459 non-null   float64
 199  GarageType_CarPort    1459 non-null   float64
 200  GarageType_Detchd     1459 non-null   float64
 201  GarageType_nan        1459 non-null   float64
 202  GarageFinish_Fin      1459 non-null   float64
 203  GarageFinish_RFn      1459 non-null   float64
 204  GarageFinish_Unf      1459 non-null   float64
 205  GarageFinish_nan      1459 non-null   float64
 206  Fence_GdPrv           1459 non-null   float64
 207  Fence_GdWo            1459 non-null   float64
 208  Fence_MnPrv           1459 non-null   float64
 209  Fence_MnWw            1459 non-null   float64
 210  Fence_nan             1459 non-null   float64
 211  MiscFeature_Gar2      1459 non-null   float64
 212  MiscFeature_Othr      1459 non-null   float64
 213  MiscFeature_Shed      1459 non-null   float64
 214  MiscFeature_TenC      1459 non-null   float64
 215  MiscFeature_nan       1459 non-null   float64
dtypes: float64(173), int64(43)
memory usage: 2.4 MB

In [201]:
test_df_2.columns[test_df_2.isnull().any()]

Index([], dtype='str')

In [210]:
# sub_preds = lr.predict(test_df_2)
# sub_preds = rf.predict(test_df_2)
sub_preds = xgb.predict(test_df_2)

In [215]:
sub_df = pd.DataFrame()
sub_df["Id"] = test_df_2.index
sub_df["SalePrice"] = sub_preds
# sub_df.to_csv("lr_submission.csv", index=False)
# sub_df.to_csv("rf_submission.csv", index=False)
sub_df.to_csv("xgb_submission.csv", index=False)