# Training data

In [75]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import optuna
import torch
import numpy as np

In [76]:
train_data = pd.read_csv("digit-recognizer/train.csv")
train_data

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [297]:
train_data["pixel300"].unique()

array([  0, 254, 253,  33, 240, 201,  88,  27,  73,  21, 128, 252, 198,
       165, 168,  46, 127,  29,  71,  17,  68, 188,  36, 255, 191,  38,
       164, 169, 133, 242, 246, 149, 101, 244, 235,  60,  93, 117, 185,
       162, 248,  13, 111, 232, 200,  25, 106,  12, 193,  65, 160, 199,
        50,  56, 231, 230,  78, 167, 170, 251, 131,  96,  66, 223, 207,
        84, 208,  48,  58, 206, 203,  10,  87,  11,  63,  61,  75,  24,
        85,  64, 217, 212,  28,  19,   3,  16,  81, 186,   4, 108,  69,
       121, 236, 192, 195, 204,   8, 129, 233, 184,  42, 158, 148, 152,
       247, 159, 218, 115, 228,  79, 135,   1,  35,  18, 238, 132, 245,
       250, 205, 202, 124, 182, 122, 142, 134, 197, 211,  76,  74,  45,
       139,  22, 166, 118, 249,  14,  43, 189, 151, 225,  80, 214, 154,
        57, 143, 156, 187,  72,  15,  89,  47, 174,   2,  39, 102, 126,
        62,  97, 163, 237,  86,  92, 104, 243,  67, 150, 221, 103, 216,
       227,  31,  83, 157, 141, 181,  49, 110, 239, 155, 196, 209,   9,
       112, 210, 146, 219,  34, 220,  53, 194,  70, 173, 179, 229, 145,
       180,   5, 241, 140, 183, 190,  23,  90, 178,  30, 171,  94,  44,
       226,  26,  59, 114, 175, 125, 147,   7, 176, 153, 100, 116, 224,
        52, 172, 130, 137, 113,  54, 213,  40,  82,  51, 107,  91, 144,
       234,  37, 136, 161,  41,  55, 177,   6, 138, 222, 120,  20, 215,
       123, 109,  98,  32,  95,  99, 119,  77, 105])

In [77]:
feature_set = train_data.drop(columns="label")
target_set = train_data["label"]

In [78]:
X_train, X_test, y_train, y_test = train_test_split(
    feature_set,
    target_set,
    random_state=42,
    shuffle=True,
    train_size=0.7
)

# Test data

In [79]:
test_data = pd.read_csv("digit-recognizer/test.csv")
test_data

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Models

#### RF

In [8]:
rf = RandomForestClassifier(
    max_depth=50,
    n_estimators=400,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=50, n_estimators=400, random_state=42)

In [9]:
predictions = rf.predict(X_train)
accuracy_score(y_pred=predictions, y_true=y_train)

1.0

In [10]:
predictions = rf.predict(X_test)
accuracy_score(y_pred=predictions, y_true=y_test)

0.9658095238095238

#### XGB

In [6]:
xgb = XGBClassifier(
    max_depth=50,
    n_estimators=10,
    num_parallel_tree=10,
    random_state=42
)

xgb.fit(X_train, y_train)

KeyboardInterrupt:

In [ ]:
predictions = xgb.predict(X_train)
accuracy_score(y_pred=predictions, y_true=y_train)

In [ ]:
predictions = xgb.predict(X_test)
accuracy_score(y_pred=predictions, y_true=y_test)

#### Neural Net

In [129]:
torch.manual_seed(0)

In [249]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_units, output_units):
        super().__init__()

        # self.layers = torch.nn.Sequential(
        #     torch.nn.Linear(input_units, 256),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(256, 128),
        #     # torch.nn.ReLU(),
        #     # torch.nn.Linear(98, 28),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(128, output_units)
        # )
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(input_units, 1024),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.3),
            torch.nn.Linear(1024, 2048),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.3),
            # torch.nn.Linear(2048, 1024),
            # torch.nn.ReLU(),
            # torch.nn.Dropout(0.3),
            torch.nn.Linear(2048, output_units)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [250]:
model = NeuralNetwork(784, 10)
model

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=784, out_features=1024, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=1024, out_features=2048, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.3, inplace=False)
    (6): Linear(in_features=2048, out_features=10, bias=True)
  )
)

In [265]:
numpy_feature_set = feature_set.to_numpy().astype(np.float32)
numpy_target_set = target_set.to_numpy().astype(np.long)

numpy_X_train, numpy_X_test, numpy_y_train, numpy_y_test = train_test_split(
    numpy_feature_set,
    numpy_target_set,
    random_state=42,
    shuffle=True,
    train_size=0.7
)

In [252]:
with torch.no_grad():
    out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
print(out)

tensor([5, 5, 2,  ..., 8, 4, 3])

In [253]:
class NNDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = NNDataset(numpy_X_train, numpy_y_train)
test_ds = NNDataset(numpy_X_test, numpy_y_test)

train_loader = torch.utils.data.DataLoader(
    dataset=train_ds,
    batch_size=32,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

test_loader = torch.utils.data.DataLoader(
    dataset=test_ds,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

In [254]:
import torch.nn.functional as F

optimizer = torch.optim.SGD(model.parameters(), lr=0.001, weight_decay=1e-3)

epochs = 15

for epoch in range(epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch {epoch+1:03d}/{epochs:03d} | Batch {batch_idx:03d}/{len(train_loader):03d} | Train loss: {loss:.2f}")

    model.eval()

Epoch 001/015 | Batch 000/918 | Train loss: 19.33
Epoch 001/015 | Batch 001/918 | Train loss: 65.84
Epoch 001/015 | Batch 002/918 | Train loss: 44.05
Epoch 001/015 | Batch 003/918 | Train loss: 33.27
Epoch 001/015 | Batch 004/918 | Train loss: 72.66
Epoch 001/015 | Batch 005/918 | Train loss: 31.64
Epoch 001/015 | Batch 006/918 | Train loss: 18.64
Epoch 001/015 | Batch 007/918 | Train loss: 22.46
Epoch 001/015 | Batch 008/918 | Train loss: 16.95
Epoch 001/015 | Batch 009/918 | Train loss: 13.50
Epoch 001/015 | Batch 010/918 | Train loss: 4.29
Epoch 001/015 | Batch 011/918 | Train loss: 2.49
Epoch 001/015 | Batch 012/918 | Train loss: 4.36
Epoch 001/015 | Batch 013/918 | Train loss: 3.54
Epoch 001/015 | Batch 014/918 | Train loss: 4.97
Epoch 001/015 | Batch 015/918 | Train loss: 3.87
Epoch 001/015 | Batch 016/918 | Train loss: 3.17
Epoch 001/015 | Batch 017/918 | Train loss: 2.63
Epoch 001/015 | Batch 018/918 | Train loss: 3.35
Epoch 001/015 | Batch 019/918 | Train loss: 1.57
Epoch 001/015 | Batch 020/918 | Train loss: 3.27
Epoch 001/015 | Batch 021/918 | Train loss: 1.82
Epoch 001/015 | Batch 022/918 | Train loss: 3.48
Epoch 001/015 | Batch 023/918 | Train loss: 0.30
Epoch 001/015 | Batch 024/918 | Train loss: 1.62
Epoch 001/015 | Batch 025/918 | Train loss: 0.57
Epoch 001/015 | Batch 026/918 | Train loss: 1.65
Epoch 001/015 | Batch 027/918 | Train loss: 3.13
Epoch 001/015 | Batch 028/918 | Train loss: 1.40
Epoch 001/015 | Batch 029/918 | Train loss: 1.87
Epoch 001/015 | Batch 030/918 | Train loss: 3.35
Epoch 001/015 | Batch 031/918 | Train loss: 1.51
Epoch 001/015 | Batch 032/918 | Train loss: 3.11
Epoch 001/015 | Batch 033/918 | Train loss: 3.37
Epoch 001/015 | Batch 034/918 | Train loss: 0.67
Epoch 001/015 | Batch 035/918 | Train loss: 1.95
Epoch 001/015 | Batch 036/918 | Train loss: 2.69
Epoch 001/015 | Batch 037/918 | Train loss: 2.02
Epoch 001/015 | Batch 038/918 | Train loss: 2.37
Epoch 001/015 | Batch 039/918 | Train loss: 2.17
Epoch 001/015 | Batch 040/918 | Train loss: 2.10
Epoch 001/015 | Batch 041/918 | Train loss: 3.39
Epoch 001/015 | Batch 042/918 | Train loss: 2.48
Epoch 001/015 | Batch 043/918 | Train loss: 1.99
Epoch 001/015 | Batch 044/918 | Train loss: 2.08
Epoch 001/015 | Batch 045/918 | Train loss: 1.48
Epoch 001/015 | Batch 046/918 | Train loss: 0.54
Epoch 001/015 | Batch 047/918 | Train loss: 1.35
Epoch 001/015 | Batch 048/918 | Train loss: 1.51
Epoch 001/015 | Batch 049/918 | Train loss: 1.25
Epoch 001/015 | Batch 050/918 | Train loss: 1.12
Epoch 001/015 | Batch 051/918 | Train loss: 1.38
Epoch 001/015 | Batch 052/918 | Train loss: 1.07
Epoch 001/015 | Batch 053/918 | Train loss: 1.19
Epoch 001/015 | Batch 054/918 | Train loss: 1.61
Epoch 001/015 | Batch 055/918 | Train loss: 0.96
Epoch 001/015 | Batch 056/918 | Train loss: 2.53
Epoch 001/015 | Batch 057/918 | Train loss: 2.94
Epoch 001/015 | Batch 058/918 | Train loss: 0.88
Epoch 001/015 | Batch 059/918 | Train loss: 2.04
Epoch 001/015 | Batch 060/918 | Train loss: 0.21
Epoch 001/015 | Batch 061/918 | Train loss: 1.95
Epoch 001/015 | Batch 062/918 | Train loss: 1.86
Epoch 001/015 | Batch 063/918 | Train loss: 1.47
Epoch 001/015 | Batch 064/918 | Train loss: 1.13
Epoch 001/015 | Batch 065/918 | Train loss: 2.53
Epoch 001/015 | Batch 066/918 | Train loss: 3.06
Epoch 001/015 | Batch 067/918 | Train loss: 1.94
Epoch 001/015 | Batch 068/918 | Train loss: 2.31
Epoch 001/015 | Batch 069/918 | Train loss: 1.79
Epoch 001/015 | Batch 070/918 | Train loss: 1.23
Epoch 001/015 | Batch 071/918 | Train loss: 1.35
Epoch 001/015 | Batch 072/918 | Train loss: 2.70
Epoch 001/015 | Batch 073/918 | Train loss: 0.88
Epoch 001/015 | Batch 074/918 | Train loss: 0.96
Epoch 001/015 | Batch 075/918 | Train loss: 1.90
Epoch 001/015 | Batch 076/918 | Train loss: 2.13
Epoch 001/015 | Batch 077/918 | Train loss: 2.06
Epoch 001/015 | Batch 078/918 | Train loss: 1.22
Epoch 001/015 | Batch 079/918 | Train loss: 2.63
Epoch 001/015 | Batch 080/918 | Train loss: 2.02
Epoch 001/015 | Batch 081/918 | Train loss: 0.95
Epoch 001/015 | Batch 082/918 | Train loss: 1.79
Epoch 001/015 | Batch 083/918 | Train loss: 1.79
Epoch 001/015 | Batch 084/918 | Train loss: 1.54
Epoch 001/015 | Batch 085/918 | Train loss: 3.01
Epoch 001/015 | Batch 086/918 | Train loss: 1.30
Epoch 001/015 | Batch 087/918 | Train loss: 1.22
Epoch 001/015 | Batch 088/918 | Train loss: 1.13
Epoch 001/015 | Batch 089/918 | Train loss: 0.45
Epoch 001/015 | Batch 090/918 | Train loss: 0.60
Epoch 001/015 | Batch 091/918 | Train loss: 2.20
Epoch 001/015 | Batch 092/918 | Train loss: 0.25
Epoch 001/015 | Batch 093/918 | Train loss: 0.47
Epoch 001/015 | Batch 094/918 | Train loss: 1.26
Epoch 001/015 | Batch 095/918 | Train loss: 1.97
Epoch 001/015 | Batch 096/918 | Train loss: 1.80
Epoch 001/015 | Batch 097/918 | Train loss: 1.27
Epoch 001/015 | Batch 098/918 | Train loss: 1.89
Epoch 001/015 | Batch 099/918 | Train loss: 1.16
Epoch 001/015 | Batch 100/918 | Train loss: 1.77
Epoch 001/015 | Batch 101/918 | Train loss: 1.74
Epoch 001/015 | Batch 102/918 | Train loss: 1.78
Epoch 001/015 | Batch 103/918 | Train loss: 0.98
Epoch 001/015 | Batch 104/918 | Train loss: 0.79
Epoch 001/015 | Batch 105/918 | Train loss: 2.03
Epoch 001/015 | Batch 106/918 | Train loss: 1.46
Epoch 001/015 | Batch 107/918 | Train loss: 0.74
Epoch 001/015 | Batch 108/918 | Train loss: 1.19
Epoch 001/015 | Batch 109/918 | Train loss: 1.46
Epoch 001/015 | Batch 110/918 | Train loss: 0.88
Epoch 001/015 | Batch 111/918 | Train loss: 0.64
Epoch 001/015 | Batch 112/918 | Train loss: 0.87
Epoch 001/015 | Batch 113/918 | Train loss: 0.88
Epoch 001/015 | Batch 114/918 | Train loss: 0.70
Epoch 001/015 | Batch 115/918 | Train loss: 1.46
Epoch 001/015 | Batch 116/918 | Train loss: 0.59
Epoch 001/015 | Batch 117/918 | Train loss: 1.18
Epoch 001/015 | Batch 118/918 | Train loss: 1.14
Epoch 001/015 | Batch 119/918 | Train loss: 0.95
Epoch 001/015 | Batch 120/918 | Train loss: 1.28
Epoch 001/015 | Batch 121/918 | Train loss: 0.90
Epoch 001/015 | Batch 122/918 | Train loss: 0.57
Epoch 001/015 | Batch 123/918 | Train loss: 0.91
Epoch 001/015 | Batch 124/918 | Train loss: 1.76
Epoch 001/015 | Batch 125/918 | Train loss: 0.74
Epoch 001/015 | Batch 126/918 | Train loss: 0.55
Epoch 001/015 | Batch 127/918 | Train loss: 1.41
Epoch 001/015 | Batch 128/918 | Train loss: 0.86
Epoch 001/015 | Batch 129/918 | Train loss: 1.08
Epoch 001/015 | Batch 130/918 | Train loss: 1.11
Epoch 001/015 | Batch 131/918 | Train loss: 3.00
Epoch 001/015 | Batch 132/918 | Train loss: 1.68
Epoch 001/015 | Batch 133/918 | Train loss: 0.87
Epoch 001/015 | Batch 134/918 | Train loss: 1.12
Epoch 001/015 | Batch 135/918 | Train loss: 1.74
Epoch 001/015 | Batch 136/918 | Train loss: 1.80
Epoch 001/015 | Batch 137/918 | Train loss: 0.82
Epoch 001/015 | Batch 138/918 | Train loss: 0.73
Epoch 001/015 | Batch 139/918 | Train loss: 1.04
Epoch 001/015 | Batch 140/918 | Train loss: 1.91
Epoch 001/015 | Batch 141/918 | Train loss: 1.04
Epoch 001/015 | Batch 142/918 | Train loss: 0.62
Epoch 001/015 | Batch 143/918 | Train loss: 1.28
Epoch 001/015 | Batch 144/918 | Train loss: 1.02
Epoch 001/015 | Batch 145/918 | Train loss: 0.59
Epoch 001/015 | Batch 146/918 | Train loss: 3.28
Epoch 001/015 | Batch 147/918 | Train loss: 0.23
Epoch 001/015 | Batch 148/918 | Train loss: 1.47
Epoch 001/015 | Batch 149/918 | Train loss: 1.17
Epoch 001/015 | Batch 150/918 | Train loss: 1.36
Epoch 001/015 | Batch 151/918 | Train loss: 0.26
Epoch 001/015 | Batch 152/918 | Train loss: 0.97
Epoch 001/015 | Batch 153/918 | Train loss: 0.58
Epoch 001/015 | Batch 154/918 | Train loss: 0.65
Epoch 001/015 | Batch 155/918 | Train loss: 0.97
Epoch 001/015 | Batch 156/918 | Train loss: 0.17
Epoch 001/015 | Batch 157/918 | Train loss: 1.20
Epoch 001/015 | Batch 158/918 | Train loss: 1.55
Epoch 001/015 | Batch 159/918 | Train loss: 1.55
Epoch 001/015 | Batch 160/918 | Train loss: 0.91
Epoch 001/015 | Batch 161/918 | Train loss: 0.77
Epoch 001/015 | Batch 162/918 | Train loss: 0.53
Epoch 001/015 | Batch 163/918 | Train loss: 0.80
Epoch 001/015 | Batch 164/918 | Train loss: 0.59
Epoch 001/015 | Batch 165/918 | Train loss: 1.09
Epoch 001/015 | Batch 166/918 | Train loss: 0.90
Epoch 001/015 | Batch 167/918 | Train loss: 0.70
Epoch 001/015 | Batch 168/918 | Train loss: 0.91
Epoch 001/015 | Batch 169/918 | Train loss: 1.29
Epoch 001/015 | Batch 170/918 | Train loss: 1.22
Epoch 001/015 | Batch 171/918 | Train loss: 0.86
Epoch 001/015 | Batch 172/918 | Train loss: 0.81
Epoch 001/015 | Batch 173/918 | Train loss: 1.06
Epoch 001/015 | Batch 174/918 | Train loss: 0.70
Epoch 001/015 | Batch 175/918 | Train loss: 1.26
Epoch 001/015 | Batch 176/918 | Train loss: 1.74
Epoch 001/015 | Batch 177/918 | Train loss: 0.95
Epoch 001/015 | Batch 178/918 | Train loss: 0.89
Epoch 001/015 | Batch 179/918 | Train loss: 0.40
Epoch 001/015 | Batch 180/918 | Train loss: 0.52
Epoch 001/015 | Batch 181/918 | Train loss: 0.21
Epoch 001/015 | Batch 182/918 | Train loss: 0.09
Epoch 001/015 | Batch 183/918 | Train loss: 1.53
Epoch 001/015 | Batch 184/918 | Train loss: 2.07
Epoch 001/015 | Batch 185/918 | Train loss: 1.14
Epoch 001/015 | Batch 186/918 | Train loss: 1.81
Epoch 001/015 | Batch 187/918 | Train loss: 0.41
Epoch 001/015 | Batch 188/918 | Train loss: 1.41
Epoch 001/015 | Batch 189/918 | Train loss: 0.86
Epoch 001/015 | Batch 190/918 | Train loss: 0.70
Epoch 001/015 | Batch 191/918 | Train loss: 1.14
Epoch 001/015 | Batch 192/918 | Train loss: 0.49
Epoch 001/015 | Batch 193/918 | Train loss: 0.29
Epoch 001/015 | Batch 194/918 | Train loss: 0.72
Epoch 001/015 | Batch 195/918 | Train loss: 1.19
Epoch 001/015 | Batch 196/918 | Train loss: 0.92
Epoch 001/015 | Batch 197/918 | Train loss: 0.74
Epoch 001/015 | Batch 198/918 | Train loss: 0.82
Epoch 001/015 | Batch 199/918 | Train loss: 1.00
Epoch 001/015 | Batch 200/918 | Train loss: 0.60
Epoch 001/015 | Batch 201/918 | Train loss: 1.88
Epoch 001/015 | Batch 202/918 | Train loss: 0.28
Epoch 001/015 | Batch 203/918 | Train loss: 0.81
Epoch 001/015 | Batch 204/918 | Train loss: 0.81
Epoch 001/015 | Batch 205/918 | Train loss: 1.92
Epoch 001/015 | Batch 206/918 | Train loss: 0.57
Epoch 001/015 | Batch 207/918 | Train loss: 1.88
Epoch 001/015 | Batch 208/918 | Train loss: 0.77
Epoch 001/015 | Batch 209/918 | Train loss: 0.87
Epoch 001/015 | Batch 210/918 | Train loss: 0.17
Epoch 001/015 | Batch 211/918 | Train loss: 0.79
Epoch 001/015 | Batch 212/918 | Train loss: 0.27
Epoch 001/015 | Batch 213/918 | Train loss: 1.09
Epoch 001/015 | Batch 214/918 | Train loss: 1.00
Epoch 001/015 | Batch 215/918 | Train loss: 1.20
Epoch 001/015 | Batch 216/918 | Train loss: 0.40
Epoch 001/015 | Batch 217/918 | Train loss: 0.71
Epoch 001/015 | Batch 218/918 | Train loss: 0.40
Epoch 001/015 | Batch 219/918 | Train loss: 0.97
Epoch 001/015 | Batch 220/918 | Train loss: 0.67
Epoch 001/015 | Batch 221/918 | Train loss: 0.47
Epoch 001/015 | Batch 222/918 | Train loss: 1.65
Epoch 001/015 | Batch 223/918 | Train loss: 0.06
Epoch 001/015 | Batch 224/918 | Train loss: 1.05
Epoch 001/015 | Batch 225/918 | Train loss: 0.48
Epoch 001/015 | Batch 226/918 | Train loss: 1.53
Epoch 001/015 | Batch 227/918 | Train loss: 1.27
Epoch 001/015 | Batch 228/918 | Train loss: 1.41
Epoch 001/015 | Batch 229/918 | Train loss: 0.67
Epoch 001/015 | Batch 230/918 | Train loss: 0.06
Epoch 001/015 | Batch 231/918 | Train loss: 1.53
Epoch 001/015 | Batch 232/918 | Train loss: 1.48
Epoch 001/015 | Batch 233/918 | Train loss: 1.00
Epoch 001/015 | Batch 234/918 | Train loss: 0.15
Epoch 001/015 | Batch 235/918 | Train loss: 0.26
Epoch 001/015 | Batch 236/918 | Train loss: 1.13
Epoch 001/015 | Batch 237/918 | Train loss: 0.31
Epoch 001/015 | Batch 238/918 | Train loss: 0.19
Epoch 001/015 | Batch 239/918 | Train loss: 1.10
Epoch 001/015 | Batch 240/918 | Train loss: 0.93
Epoch 001/015 | Batch 241/918 | Train loss: 0.30
Epoch 001/015 | Batch 242/918 | Train loss: 2.06
Epoch 001/015 | Batch 243/918 | Train loss: 0.50
Epoch 001/015 | Batch 244/918 | Train loss: 0.62
Epoch 001/015 | Batch 245/918 | Train loss: 0.03
Epoch 001/015 | Batch 246/918 | Train loss: 0.76
Epoch 001/015 | Batch 247/918 | Train loss: 0.20
Epoch 001/015 | Batch 248/918 | Train loss: 0.86
Epoch 001/015 | Batch 249/918 | Train loss: 1.91
Epoch 001/015 | Batch 250/918 | Train loss: 1.13
Epoch 001/015 | Batch 251/918 | Train loss: 0.64
Epoch 001/015 | Batch 252/918 | Train loss: 0.89
Epoch 001/015 | Batch 253/918 | Train loss: 0.54
Epoch 001/015 | Batch 254/918 | Train loss: 0.75
Epoch 001/015 | Batch 255/918 | Train loss: 1.68
Epoch 001/015 | Batch 256/918 | Train loss: 1.32
Epoch 001/015 | Batch 257/918 | Train loss: 0.67
Epoch 001/015 | Batch 258/918 | Train loss: 0.39
Epoch 001/015 | Batch 259/918 | Train loss: 1.60
Epoch 001/015 | Batch 260/918 | Train loss: 0.79
Epoch 001/015 | Batch 261/918 | Train loss: 1.15
Epoch 001/015 | Batch 262/918 | Train loss: 0.77
Epoch 001/015 | Batch 263/918 | Train loss: 0.52
Epoch 001/015 | Batch 264/918 | Train loss: 0.88
Epoch 001/015 | Batch 265/918 | Train loss: 0.81
Epoch 001/015 | Batch 266/918 | Train loss: 1.15
Epoch 001/015 | Batch 267/918 | Train loss: 0.74
Epoch 001/015 | Batch 268/918 | Train loss: 0.95
Epoch 001/015 | Batch 269/918 | Train loss: 0.04
Epoch 001/015 | Batch 270/918 | Train loss: 0.49
Epoch 001/015 | Batch 271/918 | Train loss: 0.67
Epoch 001/015 | Batch 272/918 | Train loss: 0.46
Epoch 001/015 | Batch 273/918 | Train loss: 0.21
Epoch 001/015 | Batch 274/918 | Train loss: 1.45
Epoch 001/015 | Batch 275/918 | Train loss: 2.02
Epoch 001/015 | Batch 276/918 | Train loss: 1.23
Epoch 001/015 | Batch 277/918 | Train loss: 0.94
Epoch 001/015 | Batch 278/918 | Train loss: 1.86
Epoch 001/015 | Batch 279/918 | Train loss: 0.25
Epoch 001/015 | Batch 280/918 | Train loss: 1.33
Epoch 001/015 | Batch 281/918 | Train loss: 1.34
Epoch 001/015 | Batch 282/918 | Train loss: 1.10
Epoch 001/015 | Batch 283/918 | Train loss: 1.26
Epoch 001/015 | Batch 284/918 | Train loss: 0.72
Epoch 001/015 | Batch 285/918 | Train loss: 0.53
Epoch 001/015 | Batch 286/918 | Train loss: 1.75
Epoch 001/015 | Batch 287/918 | Train loss: 0.08
Epoch 001/015 | Batch 288/918 | Train loss: 0.34
Epoch 001/015 | Batch 289/918 | Train loss: 0.18
Epoch 001/015 | Batch 290/918 | Train loss: 0.46
Epoch 001/015 | Batch 291/918 | Train loss: 0.70
Epoch 001/015 | Batch 292/918 | Train loss: 0.50
Epoch 001/015 | Batch 293/918 | Train loss: 1.60
Epoch 001/015 | Batch 294/918 | Train loss: 0.38
Epoch 001/015 | Batch 295/918 | Train loss: 0.97
Epoch 001/015 | Batch 296/918 | Train loss: 0.68
Epoch 001/015 | Batch 297/918 | Train loss: 0.94
Epoch 001/015 | Batch 298/918 | Train loss: 0.36
Epoch 001/015 | Batch 299/918 | Train loss: 0.68
Epoch 001/015 | Batch 300/918 | Train loss: 0.60
Epoch 001/015 | Batch 301/918 | Train loss: 0.55
Epoch 001/015 | Batch 302/918 | Train loss: 0.76
Epoch 001/015 | Batch 303/918 | Train loss: 0.42
Epoch 001/015 | Batch 304/918 | Train loss: 0.43
Epoch 001/015 | Batch 305/918 | Train loss: 0.15
Epoch 001/015 | Batch 306/918 | Train loss: 0.13
Epoch 001/015 | Batch 307/918 | Train loss: 1.29
Epoch 001/015 | Batch 308/918 | Train loss: 1.10
Epoch 001/015 | Batch 309/918 | Train loss: 0.58
Epoch 001/015 | Batch 310/918 | Train loss: 1.14
Epoch 001/015 | Batch 311/918 | Train loss: 0.81
Epoch 001/015 | Batch 312/918 | Train loss: 1.00
Epoch 001/015 | Batch 313/918 | Train loss: 0.33
Epoch 001/015 | Batch 314/918 | Train loss: 0.94
Epoch 001/015 | Batch 315/918 | Train loss: 1.34
Epoch 001/015 | Batch 316/918 | Train loss: 0.80
Epoch 001/015 | Batch 317/918 | Train loss: 1.06
Epoch 001/015 | Batch 318/918 | Train loss: 0.71
Epoch 001/015 | Batch 319/918 | Train loss: 1.43
Epoch 001/015 | Batch 320/918 | Train loss: 1.13
Epoch 001/015 | Batch 321/918 | Train loss: 0.85
Epoch 001/015 | Batch 322/918 | Train loss: 0.30
Epoch 001/015 | Batch 323/918 | Train loss: 0.45
Epoch 001/015 | Batch 324/918 | Train loss: 0.74
Epoch 001/015 | Batch 325/918 | Train loss: 0.70
Epoch 001/015 | Batch 326/918 | Train loss: 1.75
Epoch 001/015 | Batch 327/918 | Train loss: 0.25
Epoch 001/015 | Batch 328/918 | Train loss: 1.00
Epoch 001/015 | Batch 329/918 | Train loss: 0.64
Epoch 001/015 | Batch 330/918 | Train loss: 1.38
Epoch 001/015 | Batch 331/918 | Train loss: 0.55
Epoch 001/015 | Batch 332/918 | Train loss: 1.54
Epoch 001/015 | Batch 333/918 | Train loss: 0.43
Epoch 001/015 | Batch 334/918 | Train loss: 0.10
Epoch 001/015 | Batch 335/918 | Train loss: 2.26
Epoch 001/015 | Batch 336/918 | Train loss: 0.36
Epoch 001/015 | Batch 337/918 | Train loss: 0.36
Epoch 001/015 | Batch 338/918 | Train loss: 0.68
Epoch 001/015 | Batch 339/918 | Train loss: 0.86
Epoch 001/015 | Batch 340/918 | Train loss: 0.75
Epoch 001/015 | Batch 341/918 | Train loss: 0.07
Epoch 001/015 | Batch 342/918 | Train loss: 0.88
Epoch 001/015 | Batch 343/918 | Train loss: 0.54
Epoch 001/015 | Batch 344/918 | Train loss: 0.37
Epoch 001/015 | Batch 345/918 | Train loss: 1.21
Epoch 001/015 | Batch 346/918 | Train loss: 0.70
Epoch 001/015 | Batch 347/918 | Train loss: 0.39
Epoch 001/015 | Batch 348/918 | Train loss: 1.44
Epoch 001/015 | Batch 349/918 | Train loss: 0.74
Epoch 001/015 | Batch 350/918 | Train loss: 0.82
Epoch 001/015 | Batch 351/918 | Train loss: 1.37
Epoch 001/015 | Batch 352/918 | Train loss: 0.41
Epoch 001/015 | Batch 353/918 | Train loss: 0.87
Epoch 001/015 | Batch 354/918 | Train loss: 0.40
Epoch 001/015 | Batch 355/918 | Train loss: 0.26
Epoch 001/015 | Batch 356/918 | Train loss: 1.00
Epoch 001/015 | Batch 357/918 | Train loss: 0.70
Epoch 001/015 | Batch 358/918 | Train loss: 0.74
Epoch 001/015 | Batch 359/918 | Train loss: 0.53
Epoch 001/015 | Batch 360/918 | Train loss: 1.14
Epoch 001/015 | Batch 361/918 | Train loss: 1.03
Epoch 001/015 | Batch 362/918 | Train loss: 0.42
Epoch 001/015 | Batch 363/918 | Train loss: 0.35
Epoch 001/015 | Batch 364/918 | Train loss: 0.24
Epoch 001/015 | Batch 365/918 | Train loss: 0.45
Epoch 001/015 | Batch 366/918 | Train loss: 0.86
Epoch 001/015 | Batch 367/918 | Train loss: 0.73
Epoch 001/015 | Batch 368/918 | Train loss: 0.88
Epoch 001/015 | Batch 369/918 | Train loss: 0.74
Epoch 001/015 | Batch 370/918 | Train loss: 0.70
Epoch 001/015 | Batch 371/918 | Train loss: 0.50
Epoch 001/015 | Batch 372/918 | Train loss: 0.75
Epoch 001/015 | Batch 373/918 | Train loss: 0.63
Epoch 001/015 | Batch 374/918 | Train loss: 0.11
Epoch 001/015 | Batch 375/918 | Train loss: 0.52
Epoch 001/015 | Batch 376/918 | Train loss: 0.50
Epoch 001/015 | Batch 377/918 | Train loss: 0.26
Epoch 001/015 | Batch 378/918 | Train loss: 1.06
Epoch 001/015 | Batch 379/918 | Train loss: 0.60
Epoch 001/015 | Batch 380/918 | Train loss: 1.09
Epoch 001/015 | Batch 381/918 | Train loss: 1.15
Epoch 001/015 | Batch 382/918 | Train loss: 0.75
Epoch 001/015 | Batch 383/918 | Train loss: 0.25
Epoch 001/015 | Batch 384/918 | Train loss: 0.42
Epoch 001/015 | Batch 385/918 | Train loss: 0.58
Epoch 001/015 | Batch 386/918 | Train loss: 0.91
Epoch 001/015 | Batch 387/918 | Train loss: 0.61
Epoch 001/015 | Batch 388/918 | Train loss: 0.61
Epoch 001/015 | Batch 389/918 | Train loss: 0.45
Epoch 001/015 | Batch 390/918 | Train loss: 0.15
Epoch 001/015 | Batch 391/918 | Train loss: 0.25
Epoch 001/015 | Batch 392/918 | Train loss: 0.03
Epoch 001/015 | Batch 393/918 | Train loss: 0.50
Epoch 001/015 | Batch 394/918 | Train loss: 0.37
Epoch 001/015 | Batch 395/918 | Train loss: 0.07
Epoch 001/015 | Batch 396/918 | Train loss: 0.65
Epoch 001/015 | Batch 397/918 | Train loss: 0.31
Epoch 001/015 | Batch 398/918 | Train loss: 0.62
Epoch 001/015 | Batch 399/918 | Train loss: 0.66
Epoch 001/015 | Batch 400/918 | Train loss: 0.65
Epoch 001/015 | Batch 401/918 | Train loss: 0.09
Epoch 001/015 | Batch 402/918 | Train loss: 0.28
Epoch 001/015 | Batch 403/918 | Train loss: 0.47
Epoch 001/015 | Batch 404/918 | Train loss: 1.39
Epoch 001/015 | Batch 405/918 | Train loss: 0.42
Epoch 001/015 | Batch 406/918 | Train loss: 0.57

In [255]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_train))
    out = torch.argmax(logits, dim=1)

accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_train)

0.9989455423653866

In [256]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_test))
    out = torch.argmax(logits, dim=1)
out.shape

torch.Size([12601])

In [257]:
unique, counts = torch.unique(out, return_counts=True)

print(unique)
print(counts)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1209, 1409, 1309, 1314, 1223, 1094, 1280, 1344, 1216, 1203])

In [258]:
accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_test)

0.9746845488453297

In [ ]:
submission_test_data = test_data.to_numpy().astype(np.float32)

with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    submission_logits = model(torch.from_numpy(submission_test_data))
    submissions_out_tensor = torch.argmax(submission_logits, dim=1)
submissions_out_tensor.shape

torch.Size([28000])

In [260]:
submissions_out_numpy = submissions_out_tensor.detach().cpu().numpy()
nn_submission = pd.DataFrame()
nn_submission["ImageId"] = test_data.index + 1
nn_submission["Label"] = submissions_out_numpy
nn_submission.to_csv("nn_submission.csv", index=False)

#### CNN

In [ ]:
import torch
import numpy as np

torch.manual_seed(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class ConvNeuralNetwork(torch.nn.Module):
    def __init__(self, input_channels, output_units):
        super().__init__()

        # self.layers = torch.nn.Sequential(
        #     torch.nn.Linear(input_units, 256),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(256, 128),
        #     # torch.nn.ReLU(),
        #     # torch.nn.Linear(98, 28),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(128, output_units)
        # )
        self.layers = torch.nn.Sequential(
            torch.nn.Conv2d(in_channels=input_channels, out_channels=8, kernel_size=3, padding=1),
            torch.nn.MaxPool2d(kernel_size=2, stride=2),
            torch.nn.Conv2d(in_channels=8, out_channels=16, kernel_size=3, padding=1),
            torch.nn.MaxPool2d(kernel_size=2, stride=2),
            torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1),
            torch.nn.MaxPool2d(kernel_size=2, stride=2, ceil_mode=True),
            torch.nn.Flatten(),
            torch.nn.Linear(32 * 4 * 4, 784),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.2),
            torch.nn.Linear(784, 256),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.2),
            torch.nn.Linear(256, 128),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.2),
            # torch.nn.Linear(2048, 1024),
            # torch.nn.ReLU(),
            # torch.nn.Dropout(0.3),
            torch.nn.Linear(128, output_units)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits


model = ConvNeuralNetwork(1, 10)
# model = NeuralNetwork(4, 2)
model

numpy_feature_set = feature_set.to_numpy().astype(np.float32)
numpy_target_set = target_set.to_numpy().astype(np.long)
numpy_feature_set = numpy_feature_set.reshape(-1, 1, 28, 28)

numpy_X_train, numpy_X_test, numpy_y_train, numpy_y_test = train_test_split(
    numpy_feature_set,
    numpy_target_set,
    random_state=42,
    shuffle=True,
    train_size=0.7
)


class NNDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = NNDataset(numpy_X_train, numpy_y_train)
test_ds = NNDataset(numpy_X_test, numpy_y_test)

train_loader = torch.utils.data.DataLoader(
    dataset=train_ds,
    batch_size=32,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

test_loader = torch.utils.data.DataLoader(
    dataset=test_ds,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

model.to(device)


import torch.nn.functional as F

# optimizer = torch.optim.SGD(model.parameters(), lr=0.0001, weight_decay=1e-4)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

epochs = 15

for epoch in range(epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        features = features.to(device)
        labels = labels.to(device)
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch {epoch+1:03d}/{epochs:03d} | Batch {batch_idx:03d}/{len(train_loader):03d} | Train loss: {loss:.2f}")

    model.eval()

Epoch 001/015 | Batch 000/918 | Train loss: 2.52
Epoch 001/015 | Batch 001/918 | Train loss: 3.61
Epoch 001/015 | Batch 002/918 | Train loss: 2.65
Epoch 001/015 | Batch 003/918 | Train loss: 2.29
Epoch 001/015 | Batch 004/918 | Train loss: 2.37
Epoch 001/015 | Batch 005/918 | Train loss: 2.02
Epoch 001/015 | Batch 006/918 | Train loss: 2.18
Epoch 001/015 | Batch 007/918 | Train loss: 2.21
Epoch 001/015 | Batch 008/918 | Train loss: 2.09
Epoch 001/015 | Batch 009/918 | Train loss: 2.16
Epoch 001/015 | Batch 010/918 | Train loss: 1.93
Epoch 001/015 | Batch 011/918 | Train loss: 2.05
Epoch 001/015 | Batch 012/918 | Train loss: 1.80
Epoch 001/015 | Batch 013/918 | Train loss: 1.85
Epoch 001/015 | Batch 014/918 | Train loss: 1.57
Epoch 001/015 | Batch 015/918 | Train loss: 1.81
Epoch 001/015 | Batch 016/918 | Train loss: 1.49
Epoch 001/015 | Batch 017/918 | Train loss: 1.52
Epoch 001/015 | Batch 018/918 | Train loss: 1.48
Epoch 001/015 | Batch 019/918 | Train loss: 1.27
Epoch 001/015 | Batch 020/918 | Train loss: 1.53
Epoch 001/015 | Batch 021/918 | Train loss: 1.12
Epoch 001/015 | Batch 022/918 | Train loss: 1.03
Epoch 001/015 | Batch 023/918 | Train loss: 1.34
Epoch 001/015 | Batch 024/918 | Train loss: 0.94
Epoch 001/015 | Batch 025/918 | Train loss: 1.20
Epoch 001/015 | Batch 026/918 | Train loss: 0.66
Epoch 001/015 | Batch 027/918 | Train loss: 0.84
Epoch 001/015 | Batch 028/918 | Train loss: 0.68
Epoch 001/015 | Batch 029/918 | Train loss: 0.82
Epoch 001/015 | Batch 030/918 | Train loss: 0.79
Epoch 001/015 | Batch 031/918 | Train loss: 0.71
Epoch 001/015 | Batch 032/918 | Train loss: 0.87
Epoch 001/015 | Batch 033/918 | Train loss: 0.69
Epoch 001/015 | Batch 034/918 | Train loss: 0.62
Epoch 001/015 | Batch 035/918 | Train loss: 0.66
Epoch 001/015 | Batch 036/918 | Train loss: 0.46
Epoch 001/015 | Batch 037/918 | Train loss: 0.72
Epoch 001/015 | Batch 038/918 | Train loss: 0.79
Epoch 001/015 | Batch 039/918 | Train loss: 0.41
Epoch 001/015 | Batch 040/918 | Train loss: 0.46
Epoch 001/015 | Batch 041/918 | Train loss: 0.87
Epoch 001/015 | Batch 042/918 | Train loss: 0.51
Epoch 001/015 | Batch 043/918 | Train loss: 0.74
Epoch 001/015 | Batch 044/918 | Train loss: 0.73
Epoch 001/015 | Batch 045/918 | Train loss: 0.23
Epoch 001/015 | Batch 046/918 | Train loss: 0.45
Epoch 001/015 | Batch 047/918 | Train loss: 0.36
Epoch 001/015 | Batch 048/918 | Train loss: 0.71
Epoch 001/015 | Batch 049/918 | Train loss: 1.07
Epoch 001/015 | Batch 050/918 | Train loss: 0.43
Epoch 001/015 | Batch 051/918 | Train loss: 0.55
Epoch 001/015 | Batch 052/918 | Train loss: 0.25
Epoch 001/015 | Batch 053/918 | Train loss: 0.62
Epoch 001/015 | Batch 054/918 | Train loss: 0.28
Epoch 001/015 | Batch 055/918 | Train loss: 0.74
Epoch 001/015 | Batch 056/918 | Train loss: 1.17
Epoch 001/015 | Batch 057/918 | Train loss: 0.37
Epoch 001/015 | Batch 058/918 | Train loss: 0.99
Epoch 001/015 | Batch 059/918 | Train loss: 0.27
Epoch 001/015 | Batch 060/918 | Train loss: 0.49
Epoch 001/015 | Batch 061/918 | Train loss: 0.50
Epoch 001/015 | Batch 062/918 | Train loss: 0.38
Epoch 001/015 | Batch 063/918 | Train loss: 0.21
Epoch 001/015 | Batch 064/918 | Train loss: 0.60
Epoch 001/015 | Batch 065/918 | Train loss: 0.38
Epoch 001/015 | Batch 066/918 | Train loss: 0.55
Epoch 001/015 | Batch 067/918 | Train loss: 0.33
Epoch 001/015 | Batch 068/918 | Train loss: 0.28
Epoch 001/015 | Batch 069/918 | Train loss: 0.18
Epoch 001/015 | Batch 070/918 | Train loss: 0.77
Epoch 001/015 | Batch 071/918 | Train loss: 0.95
Epoch 001/015 | Batch 072/918 | Train loss: 0.28
Epoch 001/015 | Batch 073/918 | Train loss: 0.35
Epoch 001/015 | Batch 074/918 | Train loss: 0.53
Epoch 001/015 | Batch 075/918 | Train loss: 0.61
Epoch 001/015 | Batch 076/918 | Train loss: 0.40
Epoch 001/015 | Batch 077/918 | Train loss: 0.27
Epoch 001/015 | Batch 078/918 | Train loss: 0.38
Epoch 001/015 | Batch 079/918 | Train loss: 0.57
Epoch 001/015 | Batch 080/918 | Train loss: 0.30
Epoch 001/015 | Batch 081/918 | Train loss: 0.26
Epoch 001/015 | Batch 082/918 | Train loss: 0.19
Epoch 001/015 | Batch 083/918 | Train loss: 0.26
Epoch 001/015 | Batch 084/918 | Train loss: 0.88
Epoch 001/015 | Batch 085/918 | Train loss: 0.18
Epoch 001/015 | Batch 086/918 | Train loss: 0.12
Epoch 001/015 | Batch 087/918 | Train loss: 0.39
Epoch 001/015 | Batch 088/918 | Train loss: 0.25
Epoch 001/015 | Batch 089/918 | Train loss: 0.29
Epoch 001/015 | Batch 090/918 | Train loss: 0.34
Epoch 001/015 | Batch 091/918 | Train loss: 0.15
Epoch 001/015 | Batch 092/918 | Train loss: 0.15
Epoch 001/015 | Batch 093/918 | Train loss: 0.45
Epoch 001/015 | Batch 094/918 | Train loss: 0.57
Epoch 001/015 | Batch 095/918 | Train loss: 0.50
Epoch 001/015 | Batch 096/918 | Train loss: 0.32
Epoch 001/015 | Batch 097/918 | Train loss: 0.15
Epoch 001/015 | Batch 098/918 | Train loss: 0.20
Epoch 001/015 | Batch 099/918 | Train loss: 0.48
Epoch 001/015 | Batch 100/918 | Train loss: 0.31
Epoch 001/015 | Batch 101/918 | Train loss: 0.11
Epoch 001/015 | Batch 102/918 | Train loss: 0.28
Epoch 001/015 | Batch 103/918 | Train loss: 0.27
Epoch 001/015 | Batch 104/918 | Train loss: 0.09
Epoch 001/015 | Batch 105/918 | Train loss: 0.14
Epoch 001/015 | Batch 106/918 | Train loss: 0.27
Epoch 001/015 | Batch 107/918 | Train loss: 0.10
Epoch 001/015 | Batch 108/918 | Train loss: 0.39
Epoch 001/015 | Batch 109/918 | Train loss: 0.19
Epoch 001/015 | Batch 110/918 | Train loss: 0.32
Epoch 001/015 | Batch 111/918 | Train loss: 0.29
Epoch 001/015 | Batch 112/918 | Train loss: 0.25
Epoch 001/015 | Batch 113/918 | Train loss: 0.14
Epoch 001/015 | Batch 114/918 | Train loss: 0.26
Epoch 001/015 | Batch 115/918 | Train loss: 0.28
Epoch 001/015 | Batch 116/918 | Train loss: 0.23
Epoch 001/015 | Batch 117/918 | Train loss: 0.18
Epoch 001/015 | Batch 118/918 | Train loss: 0.17
Epoch 001/015 | Batch 119/918 | Train loss: 0.18
Epoch 001/015 | Batch 120/918 | Train loss: 0.07
Epoch 001/015 | Batch 121/918 | Train loss: 0.54
Epoch 001/015 | Batch 122/918 | Train loss: 0.07
Epoch 001/015 | Batch 123/918 | Train loss: 0.30
Epoch 001/015 | Batch 124/918 | Train loss: 0.28
Epoch 001/015 | Batch 125/918 | Train loss: 0.38
Epoch 001/015 | Batch 126/918 | Train loss: 0.11
Epoch 001/015 | Batch 127/918 | Train loss: 0.50
Epoch 001/015 | Batch 128/918 | Train loss: 0.28
Epoch 001/015 | Batch 129/918 | Train loss: 0.15
Epoch 001/015 | Batch 130/918 | Train loss: 0.56
Epoch 001/015 | Batch 131/918 | Train loss: 0.49
Epoch 001/015 | Batch 132/918 | Train loss: 0.04
Epoch 001/015 | Batch 133/918 | Train loss: 0.08
Epoch 001/015 | Batch 134/918 | Train loss: 0.12
Epoch 001/015 | Batch 135/918 | Train loss: 0.19
Epoch 001/015 | Batch 136/918 | Train loss: 0.30
Epoch 001/015 | Batch 137/918 | Train loss: 0.48
Epoch 001/015 | Batch 138/918 | Train loss: 0.09
Epoch 001/015 | Batch 139/918 | Train loss: 0.15
Epoch 001/015 | Batch 140/918 | Train loss: 0.18
Epoch 001/015 | Batch 141/918 | Train loss: 0.04
Epoch 001/015 | Batch 142/918 | Train loss: 0.37
Epoch 001/015 | Batch 143/918 | Train loss: 1.32
Epoch 001/015 | Batch 144/918 | Train loss: 0.40
Epoch 001/015 | Batch 145/918 | Train loss: 0.14
Epoch 001/015 | Batch 146/918 | Train loss: 0.53
Epoch 001/015 | Batch 147/918 | Train loss: 0.08
Epoch 001/015 | Batch 148/918 | Train loss: 0.18
Epoch 001/015 | Batch 149/918 | Train loss: 0.44
Epoch 001/015 | Batch 150/918 | Train loss: 0.14
Epoch 001/015 | Batch 151/918 | Train loss: 0.93
Epoch 001/015 | Batch 152/918 | Train loss: 0.60
Epoch 001/015 | Batch 153/918 | Train loss: 0.40
Epoch 001/015 | Batch 154/918 | Train loss: 0.75
Epoch 001/015 | Batch 155/918 | Train loss: 0.43
Epoch 001/015 | Batch 156/918 | Train loss: 0.25
Epoch 001/015 | Batch 157/918 | Train loss: 0.05
Epoch 001/015 | Batch 158/918 | Train loss: 0.11
Epoch 001/015 | Batch 159/918 | Train loss: 0.23
Epoch 001/015 | Batch 160/918 | Train loss: 0.29
Epoch 001/015 | Batch 161/918 | Train loss: 0.35
Epoch 001/015 | Batch 162/918 | Train loss: 0.39
Epoch 001/015 | Batch 163/918 | Train loss: 0.24
Epoch 001/015 | Batch 164/918 | Train loss: 0.35
Epoch 001/015 | Batch 165/918 | Train loss: 0.18
Epoch 001/015 | Batch 166/918 | Train loss: 0.21
Epoch 001/015 | Batch 167/918 | Train loss: 0.20
Epoch 001/015 | Batch 168/918 | Train loss: 0.26
Epoch 001/015 | Batch 169/918 | Train loss: 0.44
Epoch 001/015 | Batch 170/918 | Train loss: 0.18
Epoch 001/015 | Batch 171/918 | Train loss: 0.23
Epoch 001/015 | Batch 172/918 | Train loss: 0.23
Epoch 001/015 | Batch 173/918 | Train loss: 0.90
Epoch 001/015 | Batch 174/918 | Train loss: 0.45
Epoch 001/015 | Batch 175/918 | Train loss: 0.28
Epoch 001/015 | Batch 176/918 | Train loss: 0.32
Epoch 001/015 | Batch 177/918 | Train loss: 0.39
Epoch 001/015 | Batch 178/918 | Train loss: 0.11
Epoch 001/015 | Batch 179/918 | Train loss: 0.10
Epoch 001/015 | Batch 180/918 | Train loss: 0.27
Epoch 001/015 | Batch 181/918 | Train loss: 0.30
Epoch 001/015 | Batch 182/918 | Train loss: 0.24
Epoch 001/015 | Batch 183/918 | Train loss: 0.09
Epoch 001/015 | Batch 184/918 | Train loss: 0.11
Epoch 001/015 | Batch 185/918 | Train loss: 0.15
Epoch 001/015 | Batch 186/918 | Train loss: 0.28
Epoch 001/015 | Batch 187/918 | Train loss: 0.14
Epoch 001/015 | Batch 188/918 | Train loss: 0.24
Epoch 001/015 | Batch 189/918 | Train loss: 0.25
Epoch 001/015 | Batch 190/918 | Train loss: 0.52
Epoch 001/015 | Batch 191/918 | Train loss: 0.28
Epoch 001/015 | Batch 192/918 | Train loss: 0.25
Epoch 001/015 | Batch 193/918 | Train loss: 0.23
Epoch 001/015 | Batch 194/918 | Train loss: 0.21
Epoch 001/015 | Batch 195/918 | Train loss: 0.18
Epoch 001/015 | Batch 196/918 | Train loss: 0.05
Epoch 001/015 | Batch 197/918 | Train loss: 0.11
Epoch 001/015 | Batch 198/918 | Train loss: 0.37
Epoch 001/015 | Batch 199/918 | Train loss: 0.10
Epoch 001/015 | Batch 200/918 | Train loss: 0.14
Epoch 001/015 | Batch 201/918 | Train loss: 0.06
Epoch 001/015 | Batch 202/918 | Train loss: 0.58
Epoch 001/015 | Batch 203/918 | Train loss: 0.07
Epoch 001/015 | Batch 204/918 | Train loss: 0.22
Epoch 001/015 | Batch 205/918 | Train loss: 0.36
Epoch 001/015 | Batch 206/918 | Train loss: 0.45
Epoch 001/015 | Batch 207/918 | Train loss: 0.16
Epoch 001/015 | Batch 208/918 | Train loss: 0.06
Epoch 001/015 | Batch 209/918 | Train loss: 0.03
Epoch 001/015 | Batch 210/918 | Train loss: 0.16
Epoch 001/015 | Batch 211/918 | Train loss: 0.22
Epoch 001/015 | Batch 212/918 | Train loss: 0.39
Epoch 001/015 | Batch 213/918 | Train loss: 0.35
Epoch 001/015 | Batch 214/918 | Train loss: 0.21
Epoch 001/015 | Batch 215/918 | Train loss: 0.08
Epoch 001/015 | Batch 216/918 | Train loss: 0.12
Epoch 001/015 | Batch 217/918 | Train loss: 0.12
Epoch 001/015 | Batch 218/918 | Train loss: 0.21
Epoch 001/015 | Batch 219/918 | Train loss: 0.31
Epoch 001/015 | Batch 220/918 | Train loss: 0.13
Epoch 001/015 | Batch 221/918 | Train loss: 0.03
Epoch 001/015 | Batch 222/918 | Train loss: 0.08
Epoch 001/015 | Batch 223/918 | Train loss: 0.11
Epoch 001/015 | Batch 224/918 | Train loss: 0.19
Epoch 001/015 | Batch 225/918 | Train loss: 0.16
Epoch 001/015 | Batch 226/918 | Train loss: 0.07
Epoch 001/015 | Batch 227/918 | Train loss: 0.11
Epoch 001/015 | Batch 228/918 | Train loss: 0.11
Epoch 001/015 | Batch 229/918 | Train loss: 0.28
Epoch 001/015 | Batch 230/918 | Train loss: 0.24
Epoch 001/015 | Batch 231/918 | Train loss: 0.22
Epoch 001/015 | Batch 232/918 | Train loss: 0.11
Epoch 001/015 | Batch 233/918 | Train loss: 0.06
Epoch 001/015 | Batch 234/918 | Train loss: 0.49
Epoch 001/015 | Batch 235/918 | Train loss: 0.14
Epoch 001/015 | Batch 236/918 | Train loss: 0.36
Epoch 001/015 | Batch 237/918 | Train loss: 0.33
Epoch 001/015 | Batch 238/918 | Train loss: 0.15
Epoch 001/015 | Batch 239/918 | Train loss: 0.08
Epoch 001/015 | Batch 240/918 | Train loss: 0.23
Epoch 001/015 | Batch 241/918 | Train loss: 0.13
Epoch 001/015 | Batch 242/918 | Train loss: 0.20
Epoch 001/015 | Batch 243/918 | Train loss: 0.35
Epoch 001/015 | Batch 244/918 | Train loss: 0.16
Epoch 001/015 | Batch 245/918 | Train loss: 0.42
Epoch 001/015 | Batch 246/918 | Train loss: 0.09
Epoch 001/015 | Batch 247/918 | Train loss: 0.34
Epoch 001/015 | Batch 248/918 | Train loss: 0.20
Epoch 001/015 | Batch 249/918 | Train loss: 0.33
Epoch 001/015 | Batch 250/918 | Train loss: 0.24
Epoch 001/015 | Batch 251/918 | Train loss: 0.36
Epoch 001/015 | Batch 252/918 | Train loss: 0.30
Epoch 001/015 | Batch 253/918 | Train loss: 0.18
Epoch 001/015 | Batch 254/918 | Train loss: 0.49
Epoch 001/015 | Batch 255/918 | Train loss: 0.31
Epoch 001/015 | Batch 256/918 | Train loss: 0.78
Epoch 001/015 | Batch 257/918 | Train loss: 0.56
Epoch 001/015 | Batch 258/918 | Train loss: 0.55
Epoch 001/015 | Batch 259/918 | Train loss: 0.44
Epoch 001/015 | Batch 260/918 | Train loss: 0.56
Epoch 001/015 | Batch 261/918 | Train loss: 0.27
Epoch 001/015 | Batch 262/918 | Train loss: 0.33
Epoch 001/015 | Batch 263/918 | Train loss: 0.16
Epoch 001/015 | Batch 264/918 | Train loss: 0.25
Epoch 001/015 | Batch 265/918 | Train loss: 0.30
Epoch 001/015 | Batch 266/918 | Train loss: 0.07
Epoch 001/015 | Batch 267/918 | Train loss: 0.28
Epoch 001/015 | Batch 268/918 | Train loss: 0.18
Epoch 001/015 | Batch 269/918 | Train loss: 0.08
Epoch 001/015 | Batch 270/918 | Train loss: 0.08
Epoch 001/015 | Batch 271/918 | Train loss: 0.04
Epoch 001/015 | Batch 272/918 | Train loss: 0.28
Epoch 001/015 | Batch 273/918 | Train loss: 0.12
Epoch 001/015 | Batch 274/918 | Train loss: 0.38
Epoch 001/015 | Batch 275/918 | Train loss: 0.65
Epoch 001/015 | Batch 276/918 | Train loss: 0.16
Epoch 001/015 | Batch 277/918 | Train loss: 0.25
Epoch 001/015 | Batch 278/918 | Train loss: 0.20
Epoch 001/015 | Batch 279/918 | Train loss: 0.03
Epoch 001/015 | Batch 280/918 | Train loss: 0.16
Epoch 001/015 | Batch 281/918 | Train loss: 0.07
Epoch 001/015 | Batch 282/918 | Train loss: 0.23
Epoch 001/015 | Batch 283/918 | Train loss: 0.01
Epoch 001/015 | Batch 284/918 | Train loss: 0.11
Epoch 001/015 | Batch 285/918 | Train loss: 0.38
Epoch 001/015 | Batch 286/918 | Train loss: 0.21
Epoch 001/015 | Batch 287/918 | Train loss: 0.39
Epoch 001/015 | Batch 288/918 | Train loss: 0.17
Epoch 001/015 | Batch 289/918 | Train loss: 0.11
Epoch 001/015 | Batch 290/918 | Train loss: 0.18
Epoch 001/015 | Batch 291/918 | Train loss: 0.04
Epoch 001/015 | Batch 292/918 | Train loss: 0.08
Epoch 001/015 | Batch 293/918 | Train loss: 0.40
Epoch 001/015 | Batch 294/918 | Train loss: 0.12
Epoch 001/015 | Batch 295/918 | Train loss: 0.06
Epoch 001/015 | Batch 296/918 | Train loss: 0.29
Epoch 001/015 | Batch 297/918 | Train loss: 0.04
Epoch 001/015 | Batch 298/918 | Train loss: 0.09
Epoch 001/015 | Batch 299/918 | Train loss: 0.28
Epoch 001/015 | Batch 300/918 | Train loss: 0.10
Epoch 001/015 | Batch 301/918 | Train loss: 0.24
Epoch 001/015 | Batch 302/918 | Train loss: 0.28
Epoch 001/015 | Batch 303/918 | Train loss: 0.22
Epoch 001/015 | Batch 304/918 | Train loss: 0.08
Epoch 001/015 | Batch 305/918 | Train loss: 0.05
Epoch 001/015 | Batch 306/918 | Train loss: 0.08
Epoch 001/015 | Batch 307/918 | Train loss: 0.15
Epoch 001/015 | Batch 308/918 | Train loss: 0.44
Epoch 001/015 | Batch 309/918 | Train loss: 0.04
Epoch 001/015 | Batch 310/918 | Train loss: 0.01
Epoch 001/015 | Batch 311/918 | Train loss: 0.14
Epoch 001/015 | Batch 312/918 | Train loss: 0.02
Epoch 001/015 | Batch 313/918 | Train loss: 0.09
Epoch 001/015 | Batch 314/918 | Train loss: 0.13
Epoch 001/015 | Batch 315/918 | Train loss: 0.13
Epoch 001/015 | Batch 316/918 | Train loss: 0.31
Epoch 001/015 | Batch 317/918 | Train loss: 0.09
Epoch 001/015 | Batch 318/918 | Train loss: 0.79
Epoch 001/015 | Batch 319/918 | Train loss: 0.02
Epoch 001/015 | Batch 320/918 | Train loss: 0.17
Epoch 001/015 | Batch 321/918 | Train loss: 0.07
Epoch 001/015 | Batch 322/918 | Train loss: 0.05
Epoch 001/015 | Batch 323/918 | Train loss: 0.24
Epoch 001/015 | Batch 324/918 | Train loss: 0.06
Epoch 001/015 | Batch 325/918 | Train loss: 0.02
Epoch 001/015 | Batch 326/918 | Train loss: 0.04
Epoch 001/015 | Batch 327/918 | Train loss: 0.34
Epoch 001/015 | Batch 328/918 | Train loss: 0.51
Epoch 001/015 | Batch 329/918 | Train loss: 0.58
Epoch 001/015 | Batch 330/918 | Train loss: 0.19
Epoch 001/015 | Batch 331/918 | Train loss: 0.16
Epoch 001/015 | Batch 332/918 | Train loss: 0.12
Epoch 001/015 | Batch 333/918 | Train loss: 0.02
Epoch 001/015 | Batch 334/918 | Train loss: 0.24
Epoch 001/015 | Batch 335/918 | Train loss: 0.03
Epoch 001/015 | Batch 336/918 | Train loss: 0.54
Epoch 001/015 | Batch 337/918 | Train loss: 0.15
Epoch 001/015 | Batch 338/918 | Train loss: 0.10
Epoch 001/015 | Batch 339/918 | Train loss: 0.21
Epoch 001/015 | Batch 340/918 | Train loss: 0.28
Epoch 001/015 | Batch 341/918 | Train loss: 0.26
Epoch 001/015 | Batch 342/918 | Train loss: 0.37
Epoch 001/015 | Batch 343/918 | Train loss: 0.07
Epoch 001/015 | Batch 344/918 | Train loss: 0.08
Epoch 001/015 | Batch 345/918 | Train loss: 0.45
Epoch 001/015 | Batch 346/918 | Train loss: 0.03
Epoch 001/015 | Batch 347/918 | Train loss: 0.33
Epoch 001/015 | Batch 348/918 | Train loss: 0.14
Epoch 001/015 | Batch 349/918 | Train loss: 0.02
Epoch 001/015 | Batch 350/918 | Train loss: 0.10
Epoch 001/015 | Batch 351/918 | Train loss: 0.15
Epoch 001/015 | Batch 352/918 | Train loss: 0.76
Epoch 001/015 | Batch 353/918 | Train loss: 0.31
Epoch 001/015 | Batch 354/918 | Train loss: 0.22
Epoch 001/015 | Batch 355/918 | Train loss: 0.03
Epoch 001/015 | Batch 356/918 | Train loss: 0.19
Epoch 001/015 | Batch 357/918 | Train loss: 0.04
Epoch 001/015 | Batch 358/918 | Train loss: 0.01
Epoch 001/015 | Batch 359/918 | Train loss: 0.14
Epoch 001/015 | Batch 360/918 | Train loss: 0.09
Epoch 001/015 | Batch 361/918 | Train loss: 0.17
Epoch 001/015 | Batch 362/918 | Train loss: 0.17
Epoch 001/015 | Batch 363/918 | Train loss: 0.36
Epoch 001/015 | Batch 364/918 | Train loss: 0.03
Epoch 001/015 | Batch 365/918 | Train loss: 0.14
Epoch 001/015 | Batch 366/918 | Train loss: 0.04
Epoch 001/015 | Batch 367/918 | Train loss: 0.19
Epoch 001/015 | Batch 368/918 | Train loss: 0.06
Epoch 001/015 | Batch 369/918 | Train loss: 0.26
Epoch 001/015 | Batch 370/918 | Train loss: 0.16
Epoch 001/015 | Batch 371/918 | Train loss: 0.04
Epoch 001/015 | Batch 372/918 | Train loss: 0.07
Epoch 001/015 | Batch 373/918 | Train loss: 0.34
Epoch 001/015 | Batch 374/918 | Train loss: 0.16
Epoch 001/015 | Batch 375/918 | Train loss: 0.50
Epoch 001/015 | Batch 376/918 | Train loss: 0.08
Epoch 001/015 | Batch 377/918 | Train loss: 0.03
Epoch 001/015 | Batch 378/918 | Train loss: 0.25
Epoch 001/015 | Batch 379/918 | Train loss: 0.37
Epoch 001/015 | Batch 380/918 | Train loss: 0.54
Epoch 001/015 | Batch 381/918 | Train loss: 0.15
Epoch 001/015 | Batch 382/918 | Train loss: 0.09
Epoch 001/015 | Batch 383/918 | Train loss: 0.26
Epoch 001/015 | Batch 384/918 | Train loss: 0.31
Epoch 001/015 | Batch 385/918 | Train loss: 0.15
Epoch 001/015 | Batch 386/918 | Train loss: 0.14
Epoch 001/015 | Batch 387/918 | Train loss: 0.52
Epoch 001/015 | Batch 388/918 | Train loss: 0.16
Epoch 001/015 | Batch 389/918 | Train loss: 0.04
Epoch 001/015 | Batch 390/918 | Train loss: 0.07
Epoch 001/015 | Batch 391/918 | Train loss: 0.10
Epoch 001/015 | Batch 392/918 | Train loss: 0.50
Epoch 001/015 | Batch 393/918 | Train loss: 0.08
Epoch 001/015 | Batch 394/918 | Train loss: 0.07
Epoch 001/015 | Batch 395/918 | Train loss: 0.11
Epoch 001/015 | Batch 396/918 | Train loss: 0.39
Epoch 001/015 | Batch 397/918 | Train loss: 0.23
Epoch 001/015 | Batch 398/918 | Train loss: 0.29
Epoch 001/015 | Batch 399/918 | Train loss: 0.33
Epoch 001/015 | Batch 400/918 | Train loss: 0.15
Epoch 001/015 | Batch 401/918 | Train loss: 0.06
Epoch 001/015 | Batch 402/918 | Train loss: 0.16
Epoch 001/015 | Batch 403/918 | Train loss: 0.09
Epoch 001/015 | Batch 404/918 | Train loss: 0.18
Epoch 001/015 | Batch 405/918 | Train loss: 0.08
Epoch 001/015 | Batch 406/918 | Train loss: 0.47
Epoch 001/015 | Batch 407/918 | Train loss: 0.18

In [286]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_train))
    out = torch.argmax(logits, dim=1)

accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_train)

0.9939453722915745

In [287]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_test))
    out = torch.argmax(logits, dim=1)

accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_test)

0.9827791445123403

In [281]:
submission_test_data = test_data.to_numpy().astype(np.float32)

with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    submission_logits = model(torch.from_numpy(submission_test_data.reshape(-1, 1, 28, 28)))
    submissions_out_tensor = torch.argmax(submission_logits, dim=1)
submissions_out_tensor.shape

torch.Size([28000])

In [282]:
submissions_out_numpy = submissions_out_tensor.detach().cpu().numpy()
nn_submission = pd.DataFrame()
nn_submission["ImageId"] = test_data.index + 1
nn_submission["Label"] = submissions_out_numpy
nn_submission.to_csv("cnn_submission.csv", index=False)