# Training data prep

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.svm import SVC, LinearSVC

/home/unthinkable-lap/miniconda3/envs/kaggle/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_csv("titanic_data/train.csv", index_col="PassengerId")
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
data.query("(Pclass == 3) and (Cabin.notna())")

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,G6,S
395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
430,1,3,"Pickard, Mr. Berk (Berk Trembisky)",male,32.0,0,0,SOTON/O.Q. 392078,8.0500,E10,S
700,0,3,"Humblen, Mr. Adolf Mathias Nicolai Olsen",male,42.0,0,0,348121,7.6500,F G63,S
716,0,3,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.0,0,0,348124,7.6500,F G73,S
752,1,3,"Moor, Master. Meier",male,6.0,0,1,392096,12.4750,E121,S
777,0,3,"Tobin, Mr. Roger",male,NaN,0,0,383121,7.7500,F38,Q
824,1,3,"Moor, Mrs. (Beila)",female,27.0,0,1,392096,12.4750,E121,S

In [4]:
data["Cabin"] = data["Cabin"].notna().astype("int64")

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     891 non-null    int64
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [6]:
# data = data.drop(columns=["Name", "Ticket", "Fare", "Embarked", "Cabin"])
# data = data.drop(columns=["Name", "Ticket"])
data = data.dropna(subset=["Embarked"])
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [7]:
data["Embarked"].unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [8]:
data = data.replace({
    # "Sex": {"male": 0, "female": 1}
    "Embarked": {"S": 1, "C": 2, "Q": 3}
})
data["Embarked"] = data["Embarked"].astype("int64")
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,2
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,1
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,1
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,1
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,1
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0,1
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,2
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,3

In [9]:
data["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [10]:
data = data.replace({
    # "Sex": {"male": 0, "female": 1}
    "Sex": {"male": 1, "female": 2}
})
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,0,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,38.0,1,0,PC 17599,71.2833,1,2
3,1,3,"Heikkinen, Miss. Laina",2,26.0,0,0,STON/O2. 3101282,7.9250,0,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",2,35.0,1,0,113803,53.1000,1,1
5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,0,1
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,0,1
888,1,1,"Graham, Miss. Margaret Edith",2,19.0,0,0,112053,30.0000,1,1
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",2,NaN,1,2,W./C. 6607,23.4500,0,1
890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,1,2
891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,0,3

In [11]:
data.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Name      889 non-null    str
 3   Sex       889 non-null    object
 4   Age       712 non-null    float64
 5   SibSp     889 non-null    int64
 6   Parch     889 non-null    int64
 7   Ticket    889 non-null    str
 8   Fare      889 non-null    float64
 9   Cabin     889 non-null    int64
 10  Embarked  889 non-null    int64
dtypes: float64(2), int64(6), object(1), str(2)
memory usage: 83.3+ KB

In [12]:
data["Sex"] = data["Sex"].astype("int64")
# data["classist"] = data["Sex"] * data["Pclass"]

In [13]:
data.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Name      889 non-null    str
 3   Sex       889 non-null    int64
 4   Age       712 non-null    float64
 5   SibSp     889 non-null    int64
 6   Parch     889 non-null    int64
 7   Ticket    889 non-null    str
 8   Fare      889 non-null    float64
 9   Cabin     889 non-null    int64
 10  Embarked  889 non-null    int64
dtypes: float64(2), int64(7), str(2)
memory usage: 83.3 KB

In [29]:
# data["age_missing"] = data["Age"].isnull().astype("int64")
# data

In [30]:
# data.groupby("Parch")[["Parch", "Survived"]].value_counts()

In [31]:
# data.groupby("SibSp")[["SibSp", "Survived"]].value_counts()

In [ ]:
# median_age = data["Age"].median()
data["Age"] = data["Age"].fillna(data["Age"].median())
data.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Name      889 non-null    str
 3   Sex       889 non-null    int64
 4   Age       889 non-null    float64
 5   SibSp     889 non-null    int64
 6   Parch     889 non-null    int64
 7   Ticket    889 non-null    str
 8   Fare      889 non-null    float64
 9   Cabin     889 non-null    int64
 10  Embarked  889 non-null    int64
dtypes: float64(2), int64(7), str(2)
memory usage: 83.3 KB

In [ ]:
data["Age"] = (data["Age"] - data["Age"].mean()) / data["Age"].std()
data["Fare"] = (data["Fare"] - data["Fare"].mean()) / data["Fare"].std()

In [18]:
# test_x_vals = data[["Pclass", "Sex", "SibSp", "Parch", "Age", "age_missing"]]
# test_x_vals = data[["Pclass", "Sex", "SibSp", "Parch", "classist"]]
# test_x_vals = data[["Sex", "Pclass", "SibSp", "Parch", "Age"]]
# test_x_vals = data[["Sex", "Pclass", "SibSp", "Parch"]]
features = ["Sex", "Pclass", "SibSp", "Parch", "Age", "Fare", "Embarked", "Cabin"]
train_x_vals = data[features]
# test_x_vals = data[["Pclass", "Sex"]]
# "age_missing", 
y_vals = data["Survived"]

In [19]:
train_x_vals.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex       889 non-null    int64
 1   Pclass    889 non-null    int64
 2   SibSp     889 non-null    int64
 3   Parch     889 non-null    int64
 4   Age       889 non-null    float64
 5   Fare      889 non-null    float64
 6   Embarked  889 non-null    int64
 7   Cabin     889 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 62.5 KB

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    train_x_vals,
    y_vals,
    train_size=0.7,
    shuffle=True,
    random_state=42
)

# Test data prep

In [21]:
# test_data = pd.read_csv("titanic_data/test.csv", index_col="PassengerId")
test_data = pd.read_csv("titanic_data/test.csv")
test_data

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [22]:
# cleaned_test_data = test_data[["Pclass", "Sex", "SibSp", "Parch", "Age"]]
cleaned_test_data = test_data[features]
# cleaned_test_data["age_missing"] = cleaned_test_data["Age"].isnull().astype("int64")
cleaned_test_data["Age"] = cleaned_test_data["Age"].fillna(data["Age"].median())
cleaned_test_data["Fare"] = cleaned_test_data["Fare"].fillna(cleaned_test_data["Fare"].median())

cleaned_test_data["Age"] = (cleaned_test_data["Age"] - cleaned_test_data["Age"].mean()) / cleaned_test_data["Age"].std()
cleaned_test_data["Fare"] = (cleaned_test_data["Fare"] - cleaned_test_data["Fare"].mean()) / cleaned_test_data["Fare"].std()

cleaned_test_data["Cabin"] = cleaned_test_data["Cabin"].notna().astype("int64")
cleaned_test_data = cleaned_test_data.replace({
    "Sex": {"male": 1, "female": 2}
})
cleaned_test_data = cleaned_test_data.replace({
    "Embarked": {"S": 1, "C": 2, "Q": 3}
})
cleaned_test_data["Sex"] = cleaned_test_data["Sex"].astype("int64")
cleaned_test_data["Embarked"] = cleaned_test_data["Embarked"].astype("int64")
cleaned_test_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex       418 non-null    int64
 1   Pclass    418 non-null    int64
 2   SibSp     418 non-null    int64
 3   Parch     418 non-null    int64
 4   Age       418 non-null    float64
 5   Fare      418 non-null    float64
 6   Embarked  418 non-null    int64
 7   Cabin     418 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 26.3 KB

In [23]:
# data["Survived"].value_counts()

In [24]:
test_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

# Training models

#### Rf

In [25]:
rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=5,
    random_state=42
)

In [26]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_train)
accuracy_score(y_pred=y_pred, y_true=y_train)

0.8617363344051447

In [27]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_pred=y_pred, y_true=y_test)

0.8202247191011236

In [681]:
test_data_preds = rf.predict(cleaned_test_data)
test_data_preds

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [ ]:
submission = pd.DataFrame(
    {
        "PassengerId": test_data["PassengerId"],
        "Survived": test_data_preds
    }
)
submission.to_csv("rf_submission.csv", index=False)

#### XGB

In [28]:
xg_model = XGBClassifier(
    n_estimators=5,
    max_depth=3,
    random_state=42,
    num_parallel_tree=5,
)

In [29]:
xg_model.fit(X_train, y_train)
prediction = xg_model.predict(X_train)
accuracy_score(y_pred=prediction, y_true=y_train)

0.8392282958199357

In [30]:
xg_model.fit(X_train, y_train)
prediction = xg_model.predict(X_test)
accuracy_score(y_pred=prediction, y_true=y_test)

0.8202247191011236

In [97]:
xg_test_prediction = xg_model.predict(cleaned_test_data)
xg_test_prediction

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [98]:
submission = pd.DataFrame(
    {
        "PassengerId": test_data["PassengerId"],
        "Survived": xg_test_prediction
    }
)
submission.to_csv("xg_submission.csv", index=False)

#### SVC

In [31]:
# svc_model = SVC(
#     random_state=42,
#     kernel="linear",
#     C=1
# )
svc_model = LinearSVC(
    random_state=42,
    max_iter=20
)

svc_model.fit(X_test, y_test)
svc_predictions = svc_model.predict(X_test)
accuracy_score(y_pred=svc_predictions, y_true=y_test)

0.8277153558052435

In [ ]:
svc_predictions_test = svc_model.predict(cleaned_test_data)
submission = pd.DataFrame(
    {
        "PassengerId": test_data["PassengerId"],
        "Survived": svc_predictions_test
    }
)
submission.to_csv("svc_submission.csv", index=False)

# Hyperparameter tuning (Parameter search)

#### XGB

In [743]:
def objective(trial):
    param = {
        "max_depth": trial.suggest_int("max_depth", 1, 20),
        # "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
        "n_estimators": trial.suggest_int("n_estimators", 5, 50),
        # "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        # "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        # "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        # "gamma": trial.suggest_float("gamma", 0, 5),
        "num_parallel_tree": trial.suggest_int("num_parallel_tree", 5, 50)
    }
    model = XGBClassifier(
        **param,
        random_state=42
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring="accuracy").mean()
    return score

In [ ]:
study = optuna.create_study(study_name="xgboost_study", direction="maximize")
# study.optimize(objective, n_trials=1000, show_progress_bar=True, n_jobs=-1)
study.optimize(objective, n_trials=200, n_jobs=-1)

xg_best_params = study.best_params
print(f"Best params: {xg_best_params}")

[I 2026-09-29 17:55:11,515] A new study created in memory with name: xgboost_study
[W 2026-09-29 17:55:11,518] Trial 0 failed with parameters: {'max_depth': 13, 'n_estimators': 12, 'num_parallel_tree': 15} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,519] Trial 1 failed with parameters: {'max_depth': 11, 'n_estimators': 38, 'num_parallel_tree': 14} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,521] Trial 2 failed with parameters: {'max_depth': 10, 'n_estimators': 49, 'num_parallel_tree': 17} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,523] Trial 3 failed with parameters: {'max_depth': 5, 'n_estimators': 45, 'num_parallel_tree': 37} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,525] Trial 4 failed with parameters: {'max_depth': 13, 'n_estimators': 22, 'num_parallel_tree': 20} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,525] Trial 0 failed with value None.
[W 2026-09-29 17:55:11,526] Trial 5 failed with parameters: {'max_depth': 15, 'n_estimators': 16, 'num_parallel_tree': 12} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,528] Trial 6 failed with parameters: {'max_depth': 9, 'n_estimators': 14, 'num_parallel_tree': 39} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,531] Trial 7 failed with parameters: {'max_depth': 20, 'n_estimators': 48, 'num_parallel_tree': 35} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,532] Trial 8 failed with parameters: {'max_depth': 14, 'n_estimators': 43, 'num_parallel_tree': 18} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,532] Trial 1 failed with value None.
[W 2026-09-29 17:55:11,533] Trial 9 failed with parameters: {'max_depth': 15, 'n_estimators': 42, 'num_parallel_tree': 14} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,535] Trial 10 failed with parameters: {'max_depth': 13, 'n_estimators': 35, 'num_parallel_tree': 33} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,536] Trial 11 failed with parameters: {'max_depth': 19, 'n_estimators': 14, 'num_parallel_tree': 42} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,538] Trial 12 failed with parameters: {'max_depth': 4, 'n_estimators': 37, 'num_parallel_tree': 33} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 208, in wrapper
    validate_parameter_constraints(
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.
[W 2026-09-29 17:55:11,555] Trial 12 failed with value None.
[W 2026-09-29 17:55:11,540] Trial 2 failed with value None.
[W 2026-09-29 17:55:11,541] Trial 3 failed with value None.
[W 2026-09-29 17:55:11,542] Trial 4 failed with value None.
[W 2026-09-29 17:55:11,545] Trial 5 failed with value None.
[W 2026-09-29 17:55:11,546] Trial 6 failed with value None.
[W 2026-09-29 17:55:11,548] Trial 7 failed with value None.
[W 2026-09-29 17:55:11,549] Trial 8 failed with value None.
[W 2026-09-29 17:55:11,551] Trial 9 failed with value None.
[W 2026-09-29 17:55:11,553] Trial 10 failed with value None.
[W 2026-09-29 17:55:11,554] Trial 11 failed with value None.
[W 2026-09-29 17:55:11,540] Trial 13 failed with parameters: {'max_depth': 17, 'n_estimators': 10, 'num_parallel_tree': 49} because of the following error: InvalidParameterError("The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.").
Traceback (most recent call last):
  File "/home/unthinkable-lap/miniconda3/envs/titanic/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_93599/1506344599.py", line 17, in objective
    score = cross_val_score(model, X_train, y_train, cv=1, scoring="accuracy").mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

InvalidParameterError: The 'cv' parameter of cross_val_score must be an int in the range [2, inf), an object implementing 'split' and 'get_n_splits', an iterable or None. Got 1 instead.

In [ ]:
xg_test_model = XGBClassifier(
    **xg_best_params,
    random_state=42
)

xg_test_model.fit(X_train, y_train)
prediction = xg_test_model.predict(X_train)
accuracy_score(y_pred=prediction, y_true=y_train)

0.9855305466237942

In [ ]:
prediction = xg_test_model.predict(X_test)
accuracy_score(y_pred=prediction, y_true=y_test)

0.7865168539325843

#### RF

In [ ]:
def objective(trial):
    param = {
        "max_depth": trial.suggest_int("max_depth", 1, 20),
        "n_estimators": trial.suggest_int("n_estimators", 5, 100),
        # "min_samples_split": trial.suggest_int("min_samples_split", 2, 5),
        # "min_weight_fraction_leaf": trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
    }
    model = RandomForestClassifier(
        **param,
        random_state=42,
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring="accuracy").mean()
    return score

study = optuna.create_study(study_name="random_forest_study", direction="maximize")
# study.optimize(objective, n_trials=1000, show_progress_bar=True, n_jobs=-1)
study.optimize(objective, n_trials=200, n_jobs=-1)

rf_best_params = study.best_params
print(f"Best params: {rf_best_params}")

[I 2026-09-29 17:57:39,082] A new study created in memory with name: random_forest_study
[I 2026-09-29 17:57:39,849] Trial 5 finished with value: 0.7845596432552955 and parameters: {'max_depth': 2, 'n_estimators': 17}. Best is trial 5 with value: 0.7845596432552955.
[I 2026-09-29 17:57:40,483] Trial 9 finished with value: 0.8392171435649697 and parameters: {'max_depth': 12, 'n_estimators': 28}. Best is trial 9 with value: 0.8392171435649697.
[I 2026-09-29 17:57:40,761] Trial 12 finished with value: 0.8424377554812338 and parameters: {'max_depth': 9, 'n_estimators': 35}. Best is trial 12 with value: 0.8424377554812338.
[I 2026-09-29 17:57:40,957] Trial 7 finished with value: 0.8359655642264339 and parameters: {'max_depth': 7, 'n_estimators': 46}. Best is trial 12 with value: 0.8424377554812338.
[I 2026-09-29 17:57:40,960] Trial 8 finished with value: 0.8408197076675338 and parameters: {'max_depth': 13, 'n_estimators': 42}. Best is trial 12 with value: 0.8424377554812338.
[I 2026-09-29 17:57:41,082] Trial 6 finished with value: 0.8408506750898055 and parameters: {'max_depth': 16, 'n_estimators': 48}. Best is trial 12 with value: 0.8424377554812338.
[I 2026-09-29 17:57:41,193] Trial 10 finished with value: 0.8006007679920724 and parameters: {'max_depth': 3, 'n_estimators': 49}. Best is trial 12 with value: 0.8424377554812338.
[I 2026-09-29 17:57:41,202] Trial 13 finished with value: 0.845635141830794 and parameters: {'max_depth': 10, 'n_estimators': 50}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:41,409] Trial 0 finished with value: 0.8359965316487056 and parameters: {'max_depth': 18, 'n_estimators': 54}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:41,659] Trial 11 finished with value: 0.8408197076675338 and parameters: {'max_depth': 8, 'n_estimators': 56}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:42,027] Trial 2 finished with value: 0.8360042735042735 and parameters: {'max_depth': 18, 'n_estimators': 69}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:42,132] Trial 1 finished with value: 0.8376068376068376 and parameters: {'max_depth': 19, 'n_estimators': 74}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:42,272] Trial 3 finished with value: 0.8408042239563979 and parameters: {'max_depth': 13, 'n_estimators': 71}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:42,810] Trial 24 finished with value: 0.8263424377554812 and parameters: {'max_depth': 6, 'n_estimators': 13}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:43,097] Trial 4 finished with value: 0.8295553078161774 and parameters: {'max_depth': 20, 'n_estimators': 94}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:43,100] Trial 23 finished with value: 0.8279759692803171 and parameters: {'max_depth': 20, 'n_estimators': 30}. Best is trial 13 with value: 0.845635141830794.
[I 2026-09-29 17:57:43,289] Trial 26 finished with value: 0.847253189644494 and parameters: {'max_depth': 10, 'n_estimators': 18}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,507] Trial 22 finished with value: 0.8360197572154094 and parameters: {'max_depth': 15, 'n_estimators': 43}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,585] Trial 19 finished with value: 0.7877260621825838 and parameters: {'max_depth': 2, 'n_estimators': 65}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,654] Trial 14 finished with value: 0.8263501796110492 and parameters: {'max_depth': 17, 'n_estimators': 90}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,665] Trial 20 finished with value: 0.8359655642264339 and parameters: {'max_depth': 7, 'n_estimators': 54}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,799] Trial 25 finished with value: 0.8150702960485569 and parameters: {'max_depth': 4, 'n_estimators': 36}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:43,967] Trial 31 finished with value: 0.8295862752384492 and parameters: {'max_depth': 12, 'n_estimators': 7}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,042] Trial 15 finished with value: 0.8263192121887775 and parameters: {'max_depth': 5, 'n_estimators': 84}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,125] Trial 30 finished with value: 0.827991452991453 and parameters: {'max_depth': 9, 'n_estimators': 17}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,141] Trial 29 finished with value: 0.8279682274247492 and parameters: {'max_depth': 18, 'n_estimators': 19}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,257] Trial 34 finished with value: 0.8135296667905364 and parameters: {'max_depth': 15, 'n_estimators': 10}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,291] Trial 17 finished with value: 0.7861157562244517 and parameters: {'max_depth': 2, 'n_estimators': 95}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,318] Trial 35 finished with value: 0.8183451009537966 and parameters: {'max_depth': 9, 'n_estimators': 5}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,373] Trial 18 finished with value: 0.8407964821008299 and parameters: {'max_depth': 13, 'n_estimators': 78}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,556] Trial 21 finished with value: 0.842399046203394 and parameters: {'max_depth': 9, 'n_estimators': 73}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:44,693] Trial 27 finished with value: 0.8343630001238697 and parameters: {'max_depth': 7, 'n_estimators': 35}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,153] Trial 41 finished with value: 0.8263656633221851 and parameters: {'max_depth': 19, 'n_estimators': 10}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,174] Trial 33 finished with value: 0.8343939675461415 and parameters: {'max_depth': 9, 'n_estimators': 26}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,348] Trial 37 finished with value: 0.8360042735042735 and parameters: {'max_depth': 11, 'n_estimators': 17}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,464] Trial 16 finished with value: 0.8359965316487056 and parameters: {'max_depth': 14, 'n_estimators': 98}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,596] Trial 39 finished with value: 0.8327759197324415 and parameters: {'max_depth': 12, 'n_estimators': 19}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:45,891] Trial 42 finished with value: 0.7829493372971634 and parameters: {'max_depth': 1, 'n_estimators': 27}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,105] Trial 28 finished with value: 0.8375836120401338 and parameters: {'max_depth': 12, 'n_estimators': 58}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,196] Trial 40 finished with value: 0.8360197572154094 and parameters: {'max_depth': 15, 'n_estimators': 26}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,262] Trial 36 finished with value: 0.8375913538957017 and parameters: {'max_depth': 11, 'n_estimators': 41}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,365] Trial 45 finished with value: 0.8327526941657376 and parameters: {'max_depth': 7, 'n_estimators': 26}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,472] Trial 43 finished with value: 0.8376068376068376 and parameters: {'max_depth': 13, 'n_estimators': 34}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:46,571] Trial 44 finished with value: 0.8392171435649697 and parameters: {'max_depth': 9, 'n_estimators': 34}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:47,522] Trial 38 finished with value: 0.8359887897931376 and parameters: {'max_depth': 14, 'n_estimators': 62}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:47,773] Trial 53 finished with value: 0.8359810479375697 and parameters: {'max_depth': 10, 'n_estimators': 30}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:47,905] Trial 32 finished with value: 0.8392016598538338 and parameters: {'max_depth': 9, 'n_estimators': 85}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:48,384] Trial 46 finished with value: 0.8440325777282299 and parameters: {'max_depth': 10, 'n_estimators': 69}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:48,413] Trial 52 finished with value: 0.845635141830794 and parameters: {'max_depth': 9, 'n_estimators': 43}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:48,475] Trial 47 finished with value: 0.8424145299145299 and parameters: {'max_depth': 8, 'n_estimators': 65}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:49,006] Trial 54 finished with value: 0.8392094017094017 and parameters: {'max_depth': 20, 'n_estimators': 48}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:49,310] Trial 55 finished with value: 0.8375990957512697 and parameters: {'max_depth': 20, 'n_estimators': 54}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:49,507] Trial 48 finished with value: 0.8376145794624056 and parameters: {'max_depth': 16, 'n_estimators': 73}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:49,670] Trial 51 finished with value: 0.83756038647343 and parameters: {'max_depth': 6, 'n_estimators': 71}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:49,984] Trial 57 finished with value: 0.8327914034435774 and parameters: {'max_depth': 18, 'n_estimators': 60}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:50,126] Trial 59 finished with value: 0.8408197076675338 and parameters: {'max_depth': 19, 'n_estimators': 40}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:50,309] Trial 58 finished with value: 0.8456273999752261 and parameters: {'max_depth': 13, 'n_estimators': 50}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:50,376] Trial 60 finished with value: 0.8392171435649697 and parameters: {'max_depth': 20, 'n_estimators': 38}. Best is trial 26 with value: 0.847253189644494.
[I 2026-09-29 17:57:50,792] Trial 49 finished with value: 0.8488480118914902 and parameters: {'max_depth': 8, 'n_estimators': 98}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:50,988] Trial 50 finished with value: 0.8440325777282299 and parameters: {'max_depth': 9, 'n_estimators': 99}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:51,464] Trial 62 finished with value: 0.842406788058962 and parameters: {'max_depth': 9, 'n_estimators': 49}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:51,491] Trial 61 finished with value: 0.8424145299145299 and parameters: {'max_depth': 11, 'n_estimators': 51}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:51,524] Trial 70 finished with value: 0.8360274990709774 and parameters: {'max_depth': 14, 'n_estimators': 17}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:51,562] Trial 56 finished with value: 0.847253189644494 and parameters: {'max_depth': 11, 'n_estimators': 88}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:51,859] Trial 65 finished with value: 0.8392094017094017 and parameters: {'max_depth': 8, 'n_estimators': 46}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:52,129] Trial 67 finished with value: 0.8311501300631736 and parameters: {'max_depth': 6, 'n_estimators': 46}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:52,572] Trial 64 finished with value: 0.844024835872662 and parameters: {'max_depth': 10, 'n_estimators': 61}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:52,634] Trial 63 finished with value: 0.8440325777282299 and parameters: {'max_depth': 11, 'n_estimators': 69}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:52,650] Trial 66 finished with value: 0.8327681778768735 and parameters: {'max_depth': 7, 'n_estimators': 63}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:52,967] Trial 71 finished with value: 0.8344171931128453 and parameters: {'max_depth': 16, 'n_estimators': 53}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:53,083] Trial 74 finished with value: 0.8198934720673852 and parameters: {'max_depth': 5, 'n_estimators': 30}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:53,381] Trial 72 finished with value: 0.8456196581196581 and parameters: {'max_depth': 13, 'n_estimators': 51}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:53,617] Trial 69 finished with value: 0.8391939179982658 and parameters: {'max_depth': 9, 'n_estimators': 66}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:54,413] Trial 79 finished with value: 0.8408274495231017 and parameters: {'max_depth': 10, 'n_estimators': 38}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:54,442] Trial 68 finished with value: 0.845635141830794 and parameters: {'max_depth': 8, 'n_estimators': 78}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:55,671] Trial 73 finished with value: 0.8343630001238697 and parameters: {'max_depth': 7, 'n_estimators': 99}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:55,855] Trial 76 finished with value: 0.8327526941657376 and parameters: {'max_depth': 7, 'n_estimators': 83}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:55,940] Trial 83 finished with value: 0.8424300136256658 and parameters: {'max_depth': 10, 'n_estimators': 54}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:55,941] Trial 77 finished with value: 0.8424222717700979 and parameters: {'max_depth': 11, 'n_estimators': 85}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:56,159] Trial 75 finished with value: 0.8343630001238697 and parameters: {'max_depth': 7, 'n_estimators': 95}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:56,525] Trial 87 finished with value: 0.8359887897931376 and parameters: {'max_depth': 12, 'n_estimators': 46}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:56,741] Trial 84 finished with value: 0.8343939675461415 and parameters: {'max_depth': 14, 'n_estimators': 66}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:56,803] Trial 78 finished with value: 0.845635141830794 and parameters: {'max_depth': 8, 'n_estimators': 92}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:56,919] Trial 88 finished with value: 0.8344017094017094 and parameters: {'max_depth': 14, 'n_estimators': 58}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:57,063] Trial 85 finished with value: 0.8440325777282299 and parameters: {'max_depth': 11, 'n_estimators': 78}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:57,158] Trial 80 finished with value: 0.842406788058962 and parameters: {'max_depth': 10, 'n_estimators': 100}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:57,268] Trial 81 finished with value: 0.8456506255419299 and parameters: {'max_depth': 11, 'n_estimators': 99}. Best is trial 49 with value: 0.8488480118914902.
[I 2026-09-29 17:57:57,345] Trial 82 finished with value: 0.8488634956026261 and parameters: {'max_depth': 11, 'n_estimators': 98}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:57,882] Trial 86 finished with value: 0.8295630496717453 and parameters: {'max_depth': 12, 'n_estimators': 92}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:57,927] Trial 92 finished with value: 0.8375990957512697 and parameters: {'max_depth': 13, 'n_estimators': 46}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:57,950] Trial 89 finished with value: 0.8456273999752261 and parameters: {'max_depth': 13, 'n_estimators': 50}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:58,437] Trial 101 finished with value: 0.8327836615880094 and parameters: {'max_depth': 8, 'n_estimators': 20}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:59,096] Trial 93 finished with value: 0.8375913538957017 and parameters: {'max_depth': 14, 'n_estimators': 73}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:59,139] Trial 90 finished with value: 0.8359578223708658 and parameters: {'max_depth': 6, 'n_estimators': 78}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:59,242] Trial 105 finished with value: 0.8424222717700979 and parameters: {'max_depth': 10, 'n_estimators': 15}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:59,340] Trial 91 finished with value: 0.845635141830794 and parameters: {'max_depth': 8, 'n_estimators': 78}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:57:59,411] Trial 98 finished with value: 0.8424222717700979 and parameters: {'max_depth': 13, 'n_estimators': 54}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:00,270] Trial 94 finished with value: 0.8343707419794376 and parameters: {'max_depth': 14, 'n_estimators': 86}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:00,405] Trial 96 finished with value: 0.8392094017094017 and parameters: {'max_depth': 9, 'n_estimators': 90}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:00,576] Trial 97 finished with value: 0.8456273999752261 and parameters: {'max_depth': 10, 'n_estimators': 89}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:00,842] Trial 95 finished with value: 0.8424222717700979 and parameters: {'max_depth': 9, 'n_estimators': 94}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:01,387] Trial 99 finished with value: 0.8214882943143813 and parameters: {'max_depth': 5, 'n_estimators': 97}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:02,116] Trial 102 finished with value: 0.8150548123374209 and parameters: {'max_depth': 4, 'n_estimators': 89}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:02,196] Trial 100 finished with value: 0.8472222222222223 and parameters: {'max_depth': 13, 'n_estimators': 98}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:02,566] Trial 103 finished with value: 0.8488634956026261 and parameters: {'max_depth': 11, 'n_estimators': 98}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:02,612] Trial 104 finished with value: 0.8472454477889261 and parameters: {'max_depth': 8, 'n_estimators': 100}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:03,507] Trial 109 finished with value: 0.8472377059333581 and parameters: {'max_depth': 8, 'n_estimators': 79}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:03,602] Trial 106 finished with value: 0.845635141830794 and parameters: {'max_depth': 8, 'n_estimators': 94}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:03,878] Trial 108 finished with value: 0.8456506255419299 and parameters: {'max_depth': 11, 'n_estimators': 91}. Best is trial 82 with value: 0.8488634956026261.
[I 2026-09-29 17:58:04,075] Trial 110 finished with value: 0.8423913043478262 and parameters: {'max_depth': 13, 'n_estimators': 94}. Best is trial 82 with value: 0.8488634956026261.

Best params: {'max_depth': 11, 'n_estimators': 59}

In [ ]:
rf_tuned = RandomForestClassifier(
    **rf_best_params,
    random_state=42
)
rf_tuned.fit(X_train, y_train)
y_pred = rf_tuned.predict(X_train)
accuracy_score(y_pred=y_pred, y_true=y_train)

0.9565916398713826

In [ ]:
y_pred = rf_tuned.predict(X_test)
accuracy_score(y_pred=y_pred, y_true=y_test)

0.8089887640449438

##### lda

In [74]:
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report


# LDA + Logistic Regression
lda_model = Pipeline([
    ("scaler", StandardScaler()),
    ("lda", LinearDiscriminantAnalysis(n_components=1)),
    ("classifier", LogisticRegression(
        random_state=42
    ))
    # ("classifier", RandomForestClassifier(
    #     n_estimators=25,
    #     max_depth=2,
    #     random_state=42
    # ))
])




# Train
lda_model.fit(X_train, y_train)


# Predict
y_pred = lda_model.predict(X_test)


# Evaluate
accuracy = accuracy_score(y_test, y_pred)


print("LDA Accuracy:", accuracy)
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))

LDA Accuracy: 0.797752808988764

In [936]:
lda_test_prediction = lda_model.predict(cleaned_test_data)
lda_test_prediction

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [937]:
submission = pd.DataFrame(
    {
        "PassengerId": test_data["PassengerId"],
        "Survived": lda_test_prediction
    }
)
submission.to_csv("lda_submission.csv", index=False)

# NN

In [79]:
train_x_vals

,Sex,Pclass,SibSp,Parch,Age,Fare,Embarked,Cabin
PassengerId,,,,,,,,
1,1,3,1,0,-5.892881e-01,-0.499958,1,0
2,2,1,1,0,6.444852e-01,0.788503,2,1
3,2,3,0,0,-2.808448e-01,-0.486376,1,0
4,2,1,1,0,4.131527e-01,0.422623,1,1
5,1,3,0,0,4.131527e-01,-0.483861,1,0
...,...,...,...,...,...,...,...,...
887,1,2,0,0,-2.037340e-01,-0.384258,1,0
888,2,1,0,0,-8.206206e-01,-0.042189,1,1
889,2,3,1,2,-5.479054e-16,-0.173986,1,0
890,1,1,0,0,-2.808448e-01,-0.042189,2,1
891,1,3,0,0,1.818202e-01,-0.489897,3,0

In [145]:
import torch
import numpy as np
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
torch.manual_seed(0)

class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_units, output_units):
        super().__init__()

        # self.layers = torch.nn.Sequential(
        #     torch.nn.Linear(input_units, 256),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(256, 128),
        #     # torch.nn.ReLU(),
        #     # torch.nn.Linear(98, 28),
        #     torch.nn.ReLU(),
        #     torch.nn.Linear(128, output_units)
        # )
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(input_units, 32),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.2),
            torch.nn.Linear(32, 16),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.2),
            torch.nn.Linear(16, output_units)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits


model = NeuralNetwork(8, 2)
# model = NeuralNetwork(4, 2)
model

numpy_feature_set = train_x_vals.to_numpy().astype(np.float32)
numpy_target_set = y_vals.to_numpy().astype(np.long)

numpy_X_train, numpy_X_test, numpy_y_train, numpy_y_test = train_test_split(
    numpy_feature_set,
    numpy_target_set,
    random_state=42,
    shuffle=True,
    train_size=0.7
)

numpy_X_train = scaler.fit_transform(numpy_X_train)
numpy_X_test = scaler.transform(numpy_X_test)


class NNDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = NNDataset(numpy_X_train, numpy_y_train)
test_ds = NNDataset(numpy_X_test, numpy_y_test)

train_loader = torch.utils.data.DataLoader(
    dataset=train_ds,
    batch_size=8,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

test_loader = torch.utils.data.DataLoader(
    dataset=test_ds,
    batch_size=32,
    shuffle=False,
    num_workers=2
)


import torch.nn.functional as F

# optimizer = torch.optim.SGD(model.parameters(), lr=0.005)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=1e-4)

epochs = 500

for epoch in range(epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch {epoch+1:03d}/{epochs:03d} | Batch {batch_idx:03d}/{len(train_loader):03d} | Train loss: {loss:.6f}")

    model.eval()

Epoch 001/500 | Batch 000/077 | Train loss: 0.712288
Epoch 001/500 | Batch 001/077 | Train loss: 0.661511
Epoch 001/500 | Batch 002/077 | Train loss: 0.700225
Epoch 001/500 | Batch 003/077 | Train loss: 0.680272
Epoch 001/500 | Batch 004/077 | Train loss: 0.735258
Epoch 001/500 | Batch 005/077 | Train loss: 0.631393
Epoch 001/500 | Batch 006/077 | Train loss: 0.642724
Epoch 001/500 | Batch 007/077 | Train loss: 0.742257
Epoch 001/500 | Batch 008/077 | Train loss: 0.583033
Epoch 001/500 | Batch 009/077 | Train loss: 0.624915
Epoch 001/500 | Batch 010/077 | Train loss: 0.626005
Epoch 001/500 | Batch 011/077 | Train loss: 0.677602
Epoch 001/500 | Batch 012/077 | Train loss: 0.768891
Epoch 001/500 | Batch 013/077 | Train loss: 0.548415
Epoch 001/500 | Batch 014/077 | Train loss: 0.583127
Epoch 001/500 | Batch 015/077 | Train loss: 0.630203
Epoch 001/500 | Batch 016/077 | Train loss: 0.567842
Epoch 001/500 | Batch 017/077 | Train loss: 0.538804
Epoch 001/500 | Batch 018/077 | Train loss: 0.509878
Epoch 001/500 | Batch 019/077 | Train loss: 0.716351
Epoch 001/500 | Batch 020/077 | Train loss: 0.636552
Epoch 001/500 | Batch 021/077 | Train loss: 0.504425
Epoch 001/500 | Batch 022/077 | Train loss: 0.577508
Epoch 001/500 | Batch 023/077 | Train loss: 0.656414
Epoch 001/500 | Batch 024/077 | Train loss: 0.485613
Epoch 001/500 | Batch 025/077 | Train loss: 0.525910
Epoch 001/500 | Batch 026/077 | Train loss: 0.665372
Epoch 001/500 | Batch 027/077 | Train loss: 0.421492
Epoch 001/500 | Batch 028/077 | Train loss: 0.351420
Epoch 001/500 | Batch 029/077 | Train loss: 0.409235
Epoch 001/500 | Batch 030/077 | Train loss: 0.475528
Epoch 001/500 | Batch 031/077 | Train loss: 0.462461
Epoch 001/500 | Batch 032/077 | Train loss: 0.430749
Epoch 001/500 | Batch 033/077 | Train loss: 0.453599
Epoch 001/500 | Batch 034/077 | Train loss: 0.409016
Epoch 001/500 | Batch 035/077 | Train loss: 0.328286
Epoch 001/500 | Batch 036/077 | Train loss: 0.438921
Epoch 001/500 | Batch 037/077 | Train loss: 0.422926
Epoch 001/500 | Batch 038/077 | Train loss: 0.371693
Epoch 001/500 | Batch 039/077 | Train loss: 0.558552
Epoch 001/500 | Batch 040/077 | Train loss: 0.576679
Epoch 001/500 | Batch 041/077 | Train loss: 0.516847
Epoch 001/500 | Batch 042/077 | Train loss: 0.644186
Epoch 001/500 | Batch 043/077 | Train loss: 0.170888
Epoch 001/500 | Batch 044/077 | Train loss: 0.707799
Epoch 001/500 | Batch 045/077 | Train loss: 0.438266
Epoch 001/500 | Batch 046/077 | Train loss: 0.525318
Epoch 001/500 | Batch 047/077 | Train loss: 0.927540
Epoch 001/500 | Batch 048/077 | Train loss: 0.490631
Epoch 001/500 | Batch 049/077 | Train loss: 0.382331
Epoch 001/500 | Batch 050/077 | Train loss: 0.288716
Epoch 001/500 | Batch 051/077 | Train loss: 0.766175
Epoch 001/500 | Batch 052/077 | Train loss: 0.829517
Epoch 001/500 | Batch 053/077 | Train loss: 0.847841
Epoch 001/500 | Batch 054/077 | Train loss: 0.333858
Epoch 001/500 | Batch 055/077 | Train loss: 0.512593
Epoch 001/500 | Batch 056/077 | Train loss: 0.371430
Epoch 001/500 | Batch 057/077 | Train loss: 0.258599
Epoch 001/500 | Batch 058/077 | Train loss: 0.812572
Epoch 001/500 | Batch 059/077 | Train loss: 0.341848
Epoch 001/500 | Batch 060/077 | Train loss: 0.667086
Epoch 001/500 | Batch 061/077 | Train loss: 0.414025
Epoch 001/500 | Batch 062/077 | Train loss: 0.243931
Epoch 001/500 | Batch 063/077 | Train loss: 0.643774
Epoch 001/500 | Batch 064/077 | Train loss: 0.409414
Epoch 001/500 | Batch 065/077 | Train loss: 0.456585
Epoch 001/500 | Batch 066/077 | Train loss: 0.314645
Epoch 001/500 | Batch 067/077 | Train loss: 0.682527
Epoch 001/500 | Batch 068/077 | Train loss: 0.585432
Epoch 001/500 | Batch 069/077 | Train loss: 0.580058
Epoch 001/500 | Batch 070/077 | Train loss: 0.671378
Epoch 001/500 | Batch 071/077 | Train loss: 0.768005
Epoch 001/500 | Batch 072/077 | Train loss: 0.510689
Epoch 001/500 | Batch 073/077 | Train loss: 0.903728
Epoch 001/500 | Batch 074/077 | Train loss: 0.468310
Epoch 001/500 | Batch 075/077 | Train loss: 0.862133
Epoch 001/500 | Batch 076/077 | Train loss: 0.432624
Epoch 002/500 | Batch 000/077 | Train loss: 0.472593
Epoch 002/500 | Batch 001/077 | Train loss: 0.407639
Epoch 002/500 | Batch 002/077 | Train loss: 0.676113
Epoch 002/500 | Batch 003/077 | Train loss: 0.395869
Epoch 002/500 | Batch 004/077 | Train loss: 0.551350
Epoch 002/500 | Batch 005/077 | Train loss: 0.511658
Epoch 002/500 | Batch 006/077 | Train loss: 0.371601
Epoch 002/500 | Batch 007/077 | Train loss: 0.526994
Epoch 002/500 | Batch 008/077 | Train loss: 0.306321
Epoch 002/500 | Batch 009/077 | Train loss: 0.549104
Epoch 002/500 | Batch 010/077 | Train loss: 0.290905
Epoch 002/500 | Batch 011/077 | Train loss: 0.653517
Epoch 002/500 | Batch 012/077 | Train loss: 0.443817
Epoch 002/500 | Batch 013/077 | Train loss: 0.411198
Epoch 002/500 | Batch 014/077 | Train loss: 0.614797
Epoch 002/500 | Batch 015/077 | Train loss: 0.369939
Epoch 002/500 | Batch 016/077 | Train loss: 0.573056
Epoch 002/500 | Batch 017/077 | Train loss: 0.630193
Epoch 002/500 | Batch 018/077 | Train loss: 0.913075
Epoch 002/500 | Batch 019/077 | Train loss: 0.470548
Epoch 002/500 | Batch 020/077 | Train loss: 0.263465
Epoch 002/500 | Batch 021/077 | Train loss: 0.190154
Epoch 002/500 | Batch 022/077 | Train loss: 0.759963
Epoch 002/500 | Batch 023/077 | Train loss: 0.718406
Epoch 002/500 | Batch 024/077 | Train loss: 0.453304
Epoch 002/500 | Batch 025/077 | Train loss: 0.610601
Epoch 002/500 | Batch 026/077 | Train loss: 0.332030
Epoch 002/500 | Batch 027/077 | Train loss: 0.643497
Epoch 002/500 | Batch 028/077 | Train loss: 0.328324
Epoch 002/500 | Batch 029/077 | Train loss: 0.263011
Epoch 002/500 | Batch 030/077 | Train loss: 0.403863
Epoch 002/500 | Batch 031/077 | Train loss: 0.316253
Epoch 002/500 | Batch 032/077 | Train loss: 0.474747
Epoch 002/500 | Batch 033/077 | Train loss: 0.272724
Epoch 002/500 | Batch 034/077 | Train loss: 0.783350
Epoch 002/500 | Batch 035/077 | Train loss: 0.663266
Epoch 002/500 | Batch 036/077 | Train loss: 0.313640
Epoch 002/500 | Batch 037/077 | Train loss: 0.376063
Epoch 002/500 | Batch 038/077 | Train loss: 0.352564
Epoch 002/500 | Batch 039/077 | Train loss: 0.401226
Epoch 002/500 | Batch 040/077 | Train loss: 0.533426
Epoch 002/500 | Batch 041/077 | Train loss: 0.195400
Epoch 002/500 | Batch 042/077 | Train loss: 0.563124
Epoch 002/500 | Batch 043/077 | Train loss: 0.431833
Epoch 002/500 | Batch 044/077 | Train loss: 0.294925
Epoch 002/500 | Batch 045/077 | Train loss: 0.299244
Epoch 002/500 | Batch 046/077 | Train loss: 0.185170
Epoch 002/500 | Batch 047/077 | Train loss: 0.297521
Epoch 002/500 | Batch 048/077 | Train loss: 0.905766
Epoch 002/500 | Batch 049/077 | Train loss: 0.139182
Epoch 002/500 | Batch 050/077 | Train loss: 0.155341
Epoch 002/500 | Batch 051/077 | Train loss: 1.303070
Epoch 002/500 | Batch 052/077 | Train loss: 0.354215
Epoch 002/500 | Batch 053/077 | Train loss: 0.175669
Epoch 002/500 | Batch 054/077 | Train loss: 0.620544
Epoch 002/500 | Batch 055/077 | Train loss: 0.827734
Epoch 002/500 | Batch 056/077 | Train loss: 0.354107
Epoch 002/500 | Batch 057/077 | Train loss: 0.649607
Epoch 002/500 | Batch 058/077 | Train loss: 0.347827
Epoch 002/500 | Batch 059/077 | Train loss: 0.534638
Epoch 002/500 | Batch 060/077 | Train loss: 0.106353
Epoch 002/500 | Batch 061/077 | Train loss: 0.694514
Epoch 002/500 | Batch 062/077 | Train loss: 0.483276
Epoch 002/500 | Batch 063/077 | Train loss: 0.160354
Epoch 002/500 | Batch 064/077 | Train loss: 0.726441
Epoch 002/500 | Batch 065/077 | Train loss: 0.829483
Epoch 002/500 | Batch 066/077 | Train loss: 0.244873
Epoch 002/500 | Batch 067/077 | Train loss: 0.171276
Epoch 002/500 | Batch 068/077 | Train loss: 0.856299
Epoch 002/500 | Batch 069/077 | Train loss: 0.673172
Epoch 002/500 | Batch 070/077 | Train loss: 0.169331
Epoch 002/500 | Batch 071/077 | Train loss: 0.504994
Epoch 002/500 | Batch 072/077 | Train loss: 0.605689
Epoch 002/500 | Batch 073/077 | Train loss: 0.397796
Epoch 002/500 | Batch 074/077 | Train loss: 0.393099
Epoch 002/500 | Batch 075/077 | Train loss: 0.312207
Epoch 002/500 | Batch 076/077 | Train loss: 0.277971
Epoch 003/500 | Batch 000/077 | Train loss: 0.357293
Epoch 003/500 | Batch 001/077 | Train loss: 0.328400
Epoch 003/500 | Batch 002/077 | Train loss: 0.263018
Epoch 003/500 | Batch 003/077 | Train loss: 0.408169
Epoch 003/500 | Batch 004/077 | Train loss: 0.426850
Epoch 003/500 | Batch 005/077 | Train loss: 0.451581
Epoch 003/500 | Batch 006/077 | Train loss: 0.426213
Epoch 003/500 | Batch 007/077 | Train loss: 0.361046
Epoch 003/500 | Batch 008/077 | Train loss: 0.945247
Epoch 003/500 | Batch 009/077 | Train loss: 0.310448
Epoch 003/500 | Batch 010/077 | Train loss: 0.450254
Epoch 003/500 | Batch 011/077 | Train loss: 0.240591
Epoch 003/500 | Batch 012/077 | Train loss: 0.528173
Epoch 003/500 | Batch 013/077 | Train loss: 0.453960
Epoch 003/500 | Batch 014/077 | Train loss: 0.409313
Epoch 003/500 | Batch 015/077 | Train loss: 0.454643
Epoch 003/500 | Batch 016/077 | Train loss: 0.171475
Epoch 003/500 | Batch 017/077 | Train loss: 0.427221
Epoch 003/500 | Batch 018/077 | Train loss: 0.234888
Epoch 003/500 | Batch 019/077 | Train loss: 0.617703
Epoch 003/500 | Batch 020/077 | Train loss: 0.703582
Epoch 003/500 | Batch 021/077 | Train loss: 0.304861
Epoch 003/500 | Batch 022/077 | Train loss: 0.629003
Epoch 003/500 | Batch 023/077 | Train loss: 0.630717
Epoch 003/500 | Batch 024/077 | Train loss: 0.245970
Epoch 003/500 | Batch 025/077 | Train loss: 0.519659
Epoch 003/500 | Batch 026/077 | Train loss: 0.274614
Epoch 003/500 | Batch 027/077 | Train loss: 0.277625
Epoch 003/500 | Batch 028/077 | Train loss: 0.155145
Epoch 003/500 | Batch 029/077 | Train loss: 0.339594
Epoch 003/500 | Batch 030/077 | Train loss: 0.131053
Epoch 003/500 | Batch 031/077 | Train loss: 0.701691
Epoch 003/500 | Batch 032/077 | Train loss: 0.651633
Epoch 003/500 | Batch 033/077 | Train loss: 0.198332
Epoch 003/500 | Batch 034/077 | Train loss: 0.864114
Epoch 003/500 | Batch 035/077 | Train loss: 0.859969
Epoch 003/500 | Batch 036/077 | Train loss: 0.363480
Epoch 003/500 | Batch 037/077 | Train loss: 0.404036
Epoch 003/500 | Batch 038/077 | Train loss: 0.638536
Epoch 003/500 | Batch 039/077 | Train loss: 0.454654
Epoch 003/500 | Batch 040/077 | Train loss: 0.313253
Epoch 003/500 | Batch 041/077 | Train loss: 0.317812
Epoch 003/500 | Batch 042/077 | Train loss: 0.228594
Epoch 003/500 | Batch 043/077 | Train loss: 0.706878
Epoch 003/500 | Batch 044/077 | Train loss: 0.331856
Epoch 003/500 | Batch 045/077 | Train loss: 0.429960
Epoch 003/500 | Batch 046/077 | Train loss: 0.556559
Epoch 003/500 | Batch 047/077 | Train loss: 0.358590
Epoch 003/500 | Batch 048/077 | Train loss: 0.388689
Epoch 003/500 | Batch 049/077 | Train loss: 0.331010
Epoch 003/500 | Batch 050/077 | Train loss: 0.297500
Epoch 003/500 | Batch 051/077 | Train loss: 0.842641
Epoch 003/500 | Batch 052/077 | Train loss: 0.517271
Epoch 003/500 | Batch 053/077 | Train loss: 0.899593
Epoch 003/500 | Batch 054/077 | Train loss: 0.462691
Epoch 003/500 | Batch 055/077 | Train loss: 0.349311
Epoch 003/500 | Batch 056/077 | Train loss: 0.334432
Epoch 003/500 | Batch 057/077 | Train loss: 0.685100
Epoch 003/500 | Batch 058/077 | Train loss: 0.692873
Epoch 003/500 | Batch 059/077 | Train loss: 0.183025
Epoch 003/500 | Batch 060/077 | Train loss: 0.781642
Epoch 003/500 | Batch 061/077 | Train loss: 0.353564
Epoch 003/500 | Batch 062/077 | Train loss: 0.526518
Epoch 003/500 | Batch 063/077 | Train loss: 0.773557
Epoch 003/500 | Batch 064/077 | Train loss: 0.382936
Epoch 003/500 | Batch 065/077 | Train loss: 0.397985
Epoch 003/500 | Batch 066/077 | Train loss: 0.270528
Epoch 003/500 | Batch 067/077 | Train loss: 0.568010
Epoch 003/500 | Batch 068/077 | Train loss: 0.522977
Epoch 003/500 | Batch 069/077 | Train loss: 0.358407
Epoch 003/500 | Batch 070/077 | Train loss: 0.263832
Epoch 003/500 | Batch 071/077 | Train loss: 0.421094
Epoch 003/500 | Batch 072/077 | Train loss: 0.459111
Epoch 003/500 | Batch 073/077 | Train loss: 0.961888
Epoch 003/500 | Batch 074/077 | Train loss: 0.386833
Epoch 003/500 | Batch 075/077 | Train loss: 0.229686
Epoch 003/500 | Batch 076/077 | Train loss: 0.435495
Epoch 004/500 | Batch 000/077 | Train loss: 0.423640
Epoch 004/500 | Batch 001/077 | Train loss: 0.703451
Epoch 004/500 | Batch 002/077 | Train loss: 0.385462
Epoch 004/500 | Batch 003/077 | Train loss: 0.323559
Epoch 004/500 | Batch 004/077 | Train loss: 0.164223
Epoch 004/500 | Batch 005/077 | Train loss: 0.198630
Epoch 004/500 | Batch 006/077 | Train loss: 0.184273
Epoch 004/500 | Batch 007/077 | Train loss: 0.588264
Epoch 004/500 | Batch 008/077 | Train loss: 0.226617
Epoch 004/500 | Batch 009/077 | Train loss: 0.733022
Epoch 004/500 | Batch 010/077 | Train loss: 0.439258
Epoch 004/500 | Batch 011/077 | Train loss: 0.843562
Epoch 004/500 | Batch 012/077 | Train loss: 0.636368
Epoch 004/500 | Batch 013/077 | Train loss: 0.962764
Epoch 004/500 | Batch 014/077 | Train loss: 0.217311
Epoch 004/500 | Batch 015/077 | Train loss: 0.559013
Epoch 004/500 | Batch 016/077 | Train loss: 0.195864
Epoch 004/500 | Batch 017/077 | Train loss: 0.751301
Epoch 004/500 | Batch 018/077 | Train loss: 0.328878
Epoch 004/500 | Batch 019/077 | Train loss: 0.104509
Epoch 004/500 | Batch 020/077 | Train loss: 0.194492
Epoch 004/500 | Batch 021/077 | Train loss: 0.203246
Epoch 004/500 | Batch 022/077 | Train loss: 0.544097
Epoch 004/500 | Batch 023/077 | Train loss: 0.422493
Epoch 004/500 | Batch 024/077 | Train loss: 0.235536
Epoch 004/500 | Batch 025/077 | Train loss: 0.344664
Epoch 004/500 | Batch 026/077 | Train loss: 0.489861
Epoch 004/500 | Batch 027/077 | Train loss: 0.528061
Epoch 004/500 | Batch 028/077 | Train loss: 0.643166
Epoch 004/500 | Batch 029/077 | Train loss: 0.162847
Epoch 004/500 | Batch 030/077 | Train loss: 0.380944
Epoch 004/500 | Batch 031/077 | Train loss: 0.592968
Epoch 004/500 | Batch 032/077 | Train loss: 0.459055
Epoch 004/500 | Batch 033/077 | Train loss: 0.256954
Epoch 004/500 | Batch 034/077 | Train loss: 0.664182
Epoch 004/500 | Batch 035/077 | Train loss: 0.878212
Epoch 004/500 | Batch 036/077 | Train loss: 0.526697
Epoch 004/500 | Batch 037/077 | Train loss: 0.416759
Epoch 004/500 | Batch 038/077 | Train loss: 0.193553
Epoch 004/500 | Batch 039/077 | Train loss: 0.444628
Epoch 004/500 | Batch 040/077 | Train loss: 0.640722
Epoch 004/500 | Batch 041/077 | Train loss: 0.374737
Epoch 004/500 | Batch 042/077 | Train loss: 0.499711
Epoch 004/500 | Batch 043/077 | Train loss: 0.564550
Epoch 004/500 | Batch 044/077 | Train loss: 0.556255
Epoch 004/500 | Batch 045/077 | Train loss: 0.486347
Epoch 004/500 | Batch 046/077 | Train loss: 0.543041
Epoch 004/500 | Batch 047/077 | Train loss: 0.430588
Epoch 004/500 | Batch 048/077 | Train loss: 0.450080
Epoch 004/500 | Batch 049/077 | Train loss: 0.575066
Epoch 004/500 | Batch 050/077 | Train loss: 0.582977
Epoch 004/500 | Batch 051/077 | Train loss: 0.636991
Epoch 004/500 | Batch 052/077 | Train loss: 0.144580
Epoch 004/500 | Batch 053/077 | Train loss: 0.285063
Epoch 004/500 | Batch 054/077 | Train loss: 0.310455
Epoch 004/500 | Batch 055/077 | Train loss: 0.431564
Epoch 004/500 | Batch 056/077 | Train loss: 0.464824
Epoch 004/500 | Batch 057/077 | Train loss: 0.458894
Epoch 004/500 | Batch 058/077 | Train loss: 0.191411
Epoch 004/500 | Batch 059/077 | Train loss: 0.482790
Epoch 004/500 | Batch 060/077 | Train loss: 0.634019
Epoch 004/500 | Batch 061/077 | Train loss: 0.671974
Epoch 004/500 | Batch 062/077 | Train loss: 0.432855
Epoch 004/500 | Batch 063/077 | Train loss: 0.485832
Epoch 004/500 | Batch 064/077 | Train loss: 0.346686
Epoch 004/500 | Batch 065/077 | Train loss: 0.244489
Epoch 004/500 | Batch 066/077 | Train loss: 0.353346
Epoch 004/500 | Batch 067/077 | Train loss: 0.227961
Epoch 004/500 | Batch 068/077 | Train loss: 0.394817
Epoch 004/500 | Batch 069/077 | Train loss: 0.413564
Epoch 004/500 | Batch 070/077 | Train loss: 0.570527
Epoch 004/500 | Batch 071/077 | Train loss: 0.542784
Epoch 004/500 | Batch 072/077 | Train loss: 0.409760
Epoch 004/500 | Batch 073/077 | Train loss: 0.214313
Epoch 004/500 | Batch 074/077 | Train loss: 0.459433
Epoch 004/500 | Batch 075/077 | Train loss: 0.291589
Epoch 004/500 | Batch 076/077 | Train loss: 0.313532
Epoch 005/500 | Batch 000/077 | Train loss: 0.546745
Epoch 005/500 | Batch 001/077 | Train loss: 0.356720
Epoch 005/500 | Batch 002/077 | Train loss: 0.582515
Epoch 005/500 | Batch 003/077 | Train loss: 0.338303
Epoch 005/500 | Batch 004/077 | Train loss: 0.861765
Epoch 005/500 | Batch 005/077 | Train loss: 0.392689
Epoch 005/500 | Batch 006/077 | Train loss: 0.484799
Epoch 005/500 | Batch 007/077 | Train loss: 0.275439
Epoch 005/500 | Batch 008/077 | Train loss: 0.200834
Epoch 005/500 | Batch 009/077 | Train loss: 0.548323
Epoch 005/500 | Batch 010/077 | Train loss: 0.455238
Epoch 005/500 | Batch 011/077 | Train loss: 0.212714
Epoch 005/500 | Batch 012/077 | Train loss: 0.276274
Epoch 005/500 | Batch 013/077 | Train loss: 0.305207
Epoch 005/500 | Batch 014/077 | Train loss: 0.132444
Epoch 005/500 | Batch 015/077 | Train loss: 0.321209
Epoch 005/500 | Batch 016/077 | Train loss: 0.505476
Epoch 005/500 | Batch 017/077 | Train loss: 0.655512
Epoch 005/500 | Batch 018/077 | Train loss: 0.284194
Epoch 005/500 | Batch 019/077 | Train loss: 0.540988
Epoch 005/500 | Batch 020/077 | Train loss: 0.715328
Epoch 005/500 | Batch 021/077 | Train loss: 0.367731
Epoch 005/500 | Batch 022/077 | Train loss: 0.480020
Epoch 005/500 | Batch 023/077 | Train loss: 0.432109
Epoch 005/500 | Batch 024/077 | Train loss: 0.496223
Epoch 005/500 | Batch 025/077 | Train loss: 0.522744
Epoch 005/500 | Batch 026/077 | Train loss: 0.263586
Epoch 005/500 | Batch 027/077 | Train loss: 0.481944
Epoch 005/500 | Batch 028/077 | Train loss: 0.445763
Epoch 005/500 | Batch 029/077 | Train loss: 0.100263
Epoch 005/500 | Batch 030/077 | Train loss: 0.343587
Epoch 005/500 | Batch 031/077 | Train loss: 0.325362
Epoch 005/500 | Batch 032/077 | Train loss: 0.463375
Epoch 005/500 | Batch 033/077 | Train loss: 0.453053
Epoch 005/500 | Batch 034/077 | Train loss: 0.216468
Epoch 005/500 | Batch 035/077 | Train loss: 0.482206
Epoch 005/500 | Batch 036/077 | Train loss: 0.508101
Epoch 005/500 | Batch 037/077 | Train loss: 0.219986
Epoch 005/500 | Batch 038/077 | Train loss: 0.390696
Epoch 005/500 | Batch 039/077 | Train loss: 0.476311
Epoch 005/500 | Batch 040/077 | Train loss: 0.222189
Epoch 005/500 | Batch 041/077 | Train loss: 0.342545
Epoch 005/500 | Batch 042/077 | Train loss: 0.328877
Epoch 005/500 | Batch 043/077 | Train loss: 1.065079
Epoch 005/500 | Batch 044/077 | Train loss: 0.218425
Epoch 005/500 | Batch 045/077 | Train loss: 0.494208
Epoch 005/500 | Batch 046/077 | Train loss: 0.597536
Epoch 005/500 | Batch 047/077 | Train loss: 0.847991
Epoch 005/500 | Batch 048/077 | Train loss: 0.130827
Epoch 005/500 | Batch 049/077 | Train loss: 0.084094
Epoch 005/500 | Batch 050/077 | Train loss: 0.346325
Epoch 005/500 | Batch 051/077 | Train loss: 0.199072
Epoch 005/500 | Batch 052/077 | Train loss: 0.670921
Epoch 005/500 | Batch 053/077 | Train loss: 0.746163
Epoch 005/500 | Batch 054/077 | Train loss: 0.623819
Epoch 005/500 | Batch 055/077 | Train loss: 0.303417
Epoch 005/500 | Batch 056/077 | Train loss: 0.451132
Epoch 005/500 | Batch 057/077 | Train loss: 0.821410
Epoch 005/500 | Batch 058/077 | Train loss: 0.401210
Epoch 005/500 | Batch 059/077 | Train loss: 0.453318
Epoch 005/500 | Batch 060/077 | Train loss: 0.468693
Epoch 005/500 | Batch 061/077 | Train loss: 0.426096
Epoch 005/500 | Batch 062/077 | Train loss: 0.244240
Epoch 005/500 | Batch 063/077 | Train loss: 0.298957
Epoch 005/500 | Batch 064/077 | Train loss: 0.373014
Epoch 005/500 | Batch 065/077 | Train loss: 0.223085
Epoch 005/500 | Batch 066/077 | Train loss: 0.195690
Epoch 005/500 | Batch 067/077 | Train loss: 0.423873
Epoch 005/500 | Batch 068/077 | Train loss: 0.317411

In [146]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_train))
    out = torch.argmax(logits, dim=1)

accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_train)

0.887459807073955

In [147]:
with torch.no_grad():
    # out = torch.argmax(model(torch.from_numpy(numpy_X_test)), dim=1)
    logits = model(torch.from_numpy(numpy_X_test))
    out = torch.argmax(logits, dim=1)

accuracy_score(y_pred=out.detach().cpu().numpy(), y_true=numpy_y_test)

0.8052434456928839